### ISSUE TITLE
Bump up default target.jdk 

### ISSUE THREAD

**Issue by toonetown** [dnsjava/dnsjava#1]
Any chance of bumping the default target.jdk to something like 1.6 (or even 1.7) instead of 1.4?  I ask because it causes some minor issues when using within Android if the class files are an old binary level.

**Comment by kentros** [comment]
One technical detail to support bumping up is that it is currently compiling against classes that only exist in Java 1.5+.  Specifically [EllipticCurve](https://docs.oracle.com/javase/7/docs/api/java/security/spec/EllipticCurve.html) 

https://github.com/dnsjava/dnsjava/blob/d97b6a0685d59143372bb392ab591dd8dd840b61/org/xbill/DNS/DNSSEC.java#L450

In addition, it looks like a Java 1.5 method snuck in - String's [contains](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#contains(java.lang.CharSequence)) wasn't introduced until 1.5):

https://github.com/dnsjava/dnsjava/blob/d97b6a0685d59143372bb392ab591dd8dd840b61/org/xbill/DNS/TSIG.java#L490

I'd support bumping up to at least 1.5 and adding animal-sniffer to the pom.xml to help guard against any code being added that depends on a higher version of Java that is targeted.

**Comment by ibauersachs** [comment]
My current idea is as follows:
- Do a 2.1.9 release soon with minimal changes that still targets Java 1.4
- Branch to 2.2.x for maintenance, targeting Java 1.7
- Branch to 3.0.x for main development, targeting Java 1.8 or maybe 11+, with potentially breaking API changes (namely generics)

Your thoughts on this?

**Comment by kentros** [comment]
I may have jumped the gun on PR #28 .  I'm fine with your approach of a 1.4 target for the next release.

You have ultimate say, but I'm a fan of [semver](https://semver.org/), so I'd suggest we go 3.x for the Java 1.7 target branch and 4.x for the Java 8+ branch so it's very clear to consumers.

**Comment by bwelling** [comment]
I'm not sure if anyone still cares about 1.4 compatibility; 1.5 is almost 15 years old at this point.  One of the primary reasons that I tried (and failed, unfortunately) to maintain 1.4 compatibility was that the lack of generics prevented the code from being optimal for anything newer than 1.4 anyway.

Converting the code to using generics and other 1.5+ features would definitely be a good thing in a 3.0 version.  I'm not sure what the right minimum version to target is.  At the same time, it wouldn't hurt to (finally) changethe namespace to org.dnsjava.

**Comment by ibauersachs** [comment]
I don't think anybody cares either, but there's also no reason to change it for 2.1.9 in case anybody would still use it.

@bwelling do you insist on changing the namespace? This would make adopting a newer version quite a bit more complicating for existing users.

**Comment by kentros** [comment]
If you do decide to change the namespace, we could leave the old namespace and change the public methods to call their newly moved class equivalent.  Mark them Deprecated.  Downside is we carry the extra class baggage.  We could alternatively create a separate project that just has those proxy claases if we want to keep the project cleaner. 

Will we get brownie points from Bill Gates or MS if we migrate the namespace?  http://xbill.org/

**Comment by bwelling** [comment]
I wouldn’t insist on changing the namespace, but I think it would be an improvement, and the best time to do it would be when making other backwards-incompatible changes in a new major version.

**Comment by ibauersachs** [comment]
I'll consider it when I see how much impact the other API changes will have. E.g. adding generics will not necessarily break APIs.

**Comment by ibauersachs** [comment]
JDK/Language level has been lifted to 1.8 in commit f4c2dcf707ce08b6acc53d502b1d4c663d99ca43. We can track namespace and other changes in separate issues.
