### ISSUE TITLE
ReverseMap parsing?

### ISSUE THREAD

**Issue by Mygod** [dnsjava/dnsjava#103]
Could you support parsing `in-addr.arpa` addresses?

**Comment by ibauersachs** [comment]
Could you please clarify what you mean exactly, I'm not sure what's missing. Doesn't `PTRRecord` do what you need?

**Comment by Mygod** [comment]
Oh I mean like parsing a `Name` e.g. `4.3.2.1.in-addr.arpa` to an `1.2.3.4` `InetAddress`.

**Comment by Mygod** [comment]
Nice thank you!
