### ISSUE TITLE
Race condition in NioUdpClient.startUdp()

### ISSUE THREAD

**Issue by matsli** [dnsjava/dnsjava#104]
We're getting NPE on `selector` in `NioUdpClient.sendrecv()` when our service receives multiple simultaneous request on startup. The root cause seems to be a race condition concerning the `run` flag in `NioUdpClient.startUdp()`.

```
java.lang.NullPointerException: null
	at org.xbill.DNS.NioUdpClient.sendrecv(NioUdpClient.java:204)
	at org.xbill.DNS.SimpleResolver.sendAsync(SimpleResolver.java:288)
	at org.xbill.DNS.SimpleResolver.sendAsync(SimpleResolver.java:266)
	at o.x.D.ExtendedResolver$Resolution.send(ExtendedResolver.java:77)
	at o.x.D.ExtendedResolver$Resolution.startAsync(ExtendedResolver.java:83)
	at o.x.D.ExtendedResolver$Resolution.access$700(ExtendedResolver.java:31)
	at org.xbill.DNS.ExtendedResolver.sendAsync(ExtendedResolver.java:265)
	at org.xbill.DNS.Resolver.send(Resolver.java:145)
	at org.xbill.DNS.Lookup.lookup(Lookup.java:493)
	at org.xbill.DNS.Lookup.resolve(Lookup.java:543)
	at org.xbill.DNS.Lookup.run(Lookup.java:561)
	at org.xbill.DNS.Address.lookupHostName(Address.java:262)
	at org.xbill.DNS.Address.getAllByName(Address.java:326)
```

**Comment by MichaelKunze** [comment]
I can confirm this but i have no exact way to reproduce it. It happens once after server start.

**Comment by ibauersachs** [comment]
Can you check if #106 fixes this for you?

**Comment by matsli** [comment]
> 
> 
> Can you check if #106 fixes this for you?

Thanks, I haven't tested but I don't think that it's enough to solve the problem. First, I didn't notice that there is also a static `run` flag in the base class. Second, even if both flags are made perfectly thread safe, only one thread will do the initialization (as it should) and other threads will proceed to sending and receiving. There is still a risk that they reach line 204 before the initialization is done.

**Comment by ibauersachs** [comment]
> > Can you check if #106 fixes this for you?
> 
> Thanks, I haven't tested but I don't think that it's enough to solve the problem. First, I didn't notice that there is also a static `run` flag in the base class.

Yes I forgot about that as well, thanks! 🤦‍♂️

> Second, even if both flags are made perfectly thread safe, only one thread will do the initialization (as it should) and other threads will proceed to sending and receiving. There is still a risk that they reach line 204 before the initialization is done.

Indeed. Thanks again, this obviously wasn't my brightest evening ;-)

**Comment by matsli** [comment]
Thank you for fixing so quickly

**Comment by MichaelKunze** [comment]
Can you confirm it is fixed?

**Comment by matsli** [comment]
> 
> 
> Can you confirm it is fixed?

Yes, this test passes with 3.1.0 but fails (most of the time) with 3.0.2

    @Test
    public void race() throws InterruptedException {
        AtomicInteger failures = new AtomicInteger();
        int n = 10;
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(n);
        for (int i = 0; i < n; i++) {
            new Thread(() -> {
                try {
                    start.await();
                    Address.getByName("example.com");
                } catch (Exception e) {
                    failures.addAndGet(1);
                    e.printStackTrace();
                } finally {
                    done.countDown();
                }
            }).start();
        }

        Thread.sleep(100);
        start.countDown();
        done.await();
        assertThat(failures.get(), is(0));
    }
