### ISSUE TITLE
Implementing a forwarder with dnsjava

### ISSUE THREAD

**Issue by MichaelKunze** [dnsjava/dnsjava#105]
So i'm trying to implement a simple forwarder with dnsjava. I just want to make sure that i'm building the response the right way.

```
// create and send request to other dns server
private var lookup = new Lookup(request.getQuestion().getName(), request.getQuestion().getType());
lookup.setResolver(resolver);
lookup.run();

if (lookup.getResult() == Lookup.SUCCESSFUL) {
    final var response = new Message(request.getHeader().getId());

    // set some required flags
    response.getHeader().setFlag(Flags.QR);
    if (request.getHeader().getFlag(Flags.RD)) {
        response.getHeader().setFlag(Flags.RD);
    }

    // add question to response
    response.addRecord(request.getQuestion(), Section.QUESTION);

    // add everything from the answer section
    for (Record record : lookup.getAnswer()) {
        response.addRecord(record, Section.ANSWER);
    }

    return response;
} else {
    // error handling....
}
```

Would that work or is it too simple? I noticed tho, for example if i query the A-type for `www.adobe.com` that i get `lookup.getAliases()` filled, because it is actually a CNAME, which is a CNAME on a CNAME and i get the last CNAME as an `getAnswer()` 

So how do i need to add the Aliases to the response? I don't have a TTL? Any input is appreciated. Thank you!

**Comment by ibauersachs** [comment]
The TTL is not available anymore after processing through `Lookup`. You could just add it with the same TTL as with the A, but this obviously not correct.
I'm not sure what you're trying to achieve. Do you want to intercept something or manipulate the responses? If so, subclassing the `SimpleResolver` is probably a better idea.

**Comment by MichaelKunze** [comment]
Yes. I want to intercept the response and basically return what i got with a minor change. So i think using the SimpleResolver directly might help.

**Comment by ibauersachs** [comment]
Have a look at dnssecjava's [ValidatingResolver](https://github.com/ibauersachs/dnssecjava/blob/master/src/main/java/org/jitsi/dnssec/validator/ValidatingResolver.java#L1348) for an example how this can be done.
