### ISSUE TITLE
TSIG should have trace logging of calls to hmac.update()

### ISSUE THREAD

**Issue by nsayer** [dnsjava/dnsjava#109]
It would be super helpful when diagnosing problems with secure DNS to be able to log the input byte stream into the HMAC. To this end, log.trace() calls with hexdump.dump() output from the various byte arrays would  be super, super terrific.

**Comment by ibauersachs** [comment]
Have a look at the linked PR please. Anything missing in the dumps?

**Comment by nsayer** [comment]
I took a cursory look and the trace logging added looks to be exactly what I was talking about. 👍
