### ISSUE TITLE
Fail to download zonefile using AFXR

### ISSUE THREAD

**Issue by cohendekel** [dnsjava/dnsjava#117]
### Issue
   Im failing to download ```nu``` zone file using this library.

### Steps to reproduce
1. In ```dig.java#main``` increase resolver timeout
2. execute ```dig.main(new String[]{"@zonedata.iis.se","nu","AXFR"});```

### outcome
The operations runs till it passes the resolver timeout you set.

### Analisys
I think the issue is that at the end,  the resolver tries to add each record to the response ,
```
  // SimpleResolver.java
  private Message sendAXFR(Message query) throws IOException {
     ...
    for (Record record : records) {
      response.addRecord(record, Section.ANSWER);
    }
    ...
  }
```

which in turn, increases the header count:
```
// Message.java
 public void addRecord(Record r, int section) {
    ...
    header.incCount(section);
    ...
}
```

which throws exception if too many headers (records) exists:
```
// Header.java
void incCount(int field) {
    if (counts[field] == 0xFFFF) {
      throw new IllegalStateException("DNS section count cannot be incremented");
    }
    ...
}
```

**Comment by ibauersachs** [comment]
I've fixed the cmdline tool, but if you're using AXFR in your own code, I'd suggest you avoid using the dig-tool and call `ZoneTransferIn.newAXFR` yourself, using a custom `ZoneTransferHandler`.
