### ISSUE TITLE
release 3.3.0?

### ISSUE THREAD

**Issue by aaylward** [dnsjava/dnsjava#121]
Hi @ibauersachs  -- thanks for maintaining this library! Would you please cut a release with SVCB and HTTPS support?

Thanks again,
Andy

**Comment by aaylward** [comment]
thanks for getting back to me! do you have a timeline in mind?

**Comment by ibauersachs** [comment]
No, I don't. It's a gut feeling when I'll do it.

**Comment by hisener** [comment]
> No, I don't. It's a gut feeling when I'll do it.

Do you think it will be soon? :) I am also waiting for https://github.com/dnsjava/dnsjava/issues/118.

**Comment by ibauersachs** [comment]
I'm working on finding a solution to the open DoH issues which I want to include in the next release.

**Comment by ibauersachs** [comment]
@hisener @adam-stoler @aaylward 
v3.3.0 is released, it should appear soon on Maven Central.

**Comment by aaylward** [comment]
Thanks @ibauersachs !
