### ISSUE TITLE
DohResolver's returning wrong Answer to queries

### ISSUE THREAD

**Issue by n0ise9914** [dnsjava/dnsjava#122]
I'm using the cloudflare's DoT:
https://cloudflare-dns.com/dns-query

At the client side i'm facing this error:
dns.resolver.NoNameservers: All nameservers failed to answer the query yahoo.com. IN A: Server 127.0.0.1 UDP port 53 answered A DNS query response does not respond to the question asked.

I've found out that the ID in header of DohResolver's response was null
manually setting the ID from Request worked: `response.getHeader().setID(request.getHeader().getID());`

but is it the expected behaviour?

**Comment by ibauersachs** [comment]
Sorry, but I'm not sure what you're trying to say. The error message you're quoting is using UDP and seems to be from dnspython (it definitely isn't from dnsjava). See below for an example of dnsjava using the DohResolver. The ID in the response is not `null` but zero (0), which is indeed expected as per [rfc8484, section 4.1](https://tools.ietf.org/html/rfc8484#section-4.1):

>   In order to maximize HTTP cache friendliness, DoH clients using media
   formats that include the ID field from the DNS message header, such
   as "application/dns-message", SHOULD use a DNS ID of 0 in every DNS
   request.  HTTP correlates the request and response, thus eliminating
   the need for the ID in a media type such as "application/dns-
   message".  The use of a varying DNS ID can cause semantically
   equivalent DNS queries to be cached separately.


```java
package org.xbill.DNS;

import java.io.IOException;

public class DohTest {
  public static void main(String[] args) throws IOException {
    DohResolver doh = new DohResolver("https://cloudflare-dns.com/dns-query");
    Message result =
        doh.send(
            Message.newQuery(
                Record.newRecord(Name.fromConstantString("yahoo.com."), Type.A, DClass.IN)));
    System.out.println(result);
  }
}

```

```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 0
;; flags: qr rd ra ; qd: 1 an: 6 au: 0 ad: 1 
;; QUESTIONS:
;;	yahoo.com., type = A, class = IN

;; ANSWERS:
yahoo.com.		1060	IN	A	74.6.231.20
yahoo.com.		1060	IN	A	74.6.231.21
yahoo.com.		1060	IN	A	98.137.11.164
yahoo.com.		1060	IN	A	98.137.11.163
yahoo.com.		1060	IN	A	74.6.143.26
yahoo.com.		1060	IN	A	74.6.143.25

;; AUTHORITY RECORDS:

;; ADDITIONAL RECORDS:
.			0	CLASS1232	OPT	 ; payload 1232, xrcode 0, version 0, flags 0

;; Message size: 143 bytes
```

**Comment by n0ise9914** [comment]
I made a test dns server using dnsjava to forward request's coming to traditional dns server to another DoH server and return the response back to the client, And you're right, I've used the dnspython to test this server.
but i didn't know about this rfc section, thank you

**Comment by ibauersachs** [comment]
In that case you'll need to remember the ID of the query coming via UDP before sending it to the DohResolver and then re-inject it before replying to the UDP client.
