### ISSUE TITLE
Custom caching machanism

### ISSUE THREAD

**Issue by n0ise9914** [dnsjava/dnsjava#124]
We can't override Cache.java methods because almost all important methods are private
Also the Cache.java isn't implementing any interface, so there is no way to override it and pass custom Cache class to Lookup.java

**Comment by ibauersachs** [comment]
What exactly is missing in the existing `Cache` class?

**Comment by mdk-ML** [comment]
How long is the default expire time about records?

**Comment by n0ise9914** [comment]
As a standard dns cache "it's acting very well" but I've just needed something totally different
Incoming dns queries to expired record's should wait for the resolver to update them (causing delay every little period of time, TTL)
I just wanted to answer the queries and then update the record in background
I've cloned the project and made changes to my fork, THANK YOU

**Comment by ibauersachs** [comment]
> How long is the default expire time about records?

It's the TTL of the Record, there is no default.

**Comment by ibauersachs** [comment]
> As a standard dns cache "it's acting very well" but I've just needed something totally different
> Incoming dns queries to expired record's should wait for the resolver to update them (causing delay every little period of time, TTL)
> I just wanted to answer the queries and then update the record in background
> I've cloned the project and made the changes to my fork, THANK YOU

How big is your cache? If a cache lookup/update is slower than a network roundtrip, we should start investigating there.

**Comment by mdk-ML** [comment]
> > How long is the default expire time about records?
> 
> It's the TTL of the Record, there is no default.

Means that the data in the cache is always valid?
When I change the TXT of the domain , will the next query change?

**Comment by ibauersachs** [comment]
> > > How long is the default expire time about records?
> > 
> > 
> > It's the TTL of the Record, there is no default.
> 
> Means that the data in the cache is always valid?
> When I change the TXT of the domain , will the next query change?

It depends.
If the TTL has expired, dnsjava will reissue the query and you'll see the change. If the TTL has not expired, you won't see the change. This is standard DNS behaviour.

Also, please do not hijack issues. Your question is not related to the original issue.

**Comment by n0ise9914** [comment]
> > As a standard dns cache "it's acting very well" but I've just needed something totally different
> > Incoming dns queries to expired record's should wait for the resolver to update them (causing delay every little period of time, TTL)
> > I just wanted to answer the queries and then update the record in background
> > I've cloned the project and made the changes to my fork, THANK YOU
> 
> How big is your cache? If a cache lookup/update is slower than a network roundtrip, we should start investigating there.

There is no problem with searching in cache (its lightweight and very fast)
The problem is the cache is frequently getting updated on record's with low TTL (causing periodic delay)
for example in our bad network querying google.com takes about 100-200ms, and it's TTL is 5min
Causing the client to face delay of around 150ms each 5min, i've made some changes to answer the client before updating the cache via resolver

**Comment by ibauersachs** [comment]
I'm confused. If the TTL is 5min and the record expired in the cache, you need to do a lookup. If this lookup takes 150ms, then this is still the minimum delay for the client to receive the answer. Additional time from the cache would only be added to the total time AFTER the lookup.
Are you keeping Records in the beyond their original TTL? If so, that would violate the spec.

In any case, I'd be happy to look at a PR if you think your changes would make sense for the general public.
