### ISSUE TITLE
Failed simple resolver

### ISSUE THREAD

**Issue by devrivne** [dnsjava/dnsjava#131]
One more issue I've faced with simple resolver:

```
Failed to resolve google.com./A, id=19136 with resolver 0 (SimpleResolver [/1.1.1.1:53]) on attempt 1 of 0, reason=java.io.EOFException: Client is closing

...

2020/09/14 19:49:03.312997 [INFO] (runner) child process died
--
2020/09/14 19:49:03.313070 [ERR] (cli) child process died with exit code 255
```

Reproduced multiple times with high prolonged load.
Any suggestions on how to fix that?

**Comment by ibauersachs** [comment]
Can you please provide more details what you are doing? And please also note that public resolvers like Cloudflare (which you seem to be using) or Google do rate limiting. For example, I would not be able to run the dnsssecjava testsuite against either of those resolvers.

**Comment by devrivne** [comment]
It was an example. We're using our custom servers that are hosted on the same HW w/o any rate limits.
On python I could resolve any num of hosts, it depends only on cores.

Code is the same as for DOH resolver I've provided in a previous issue.
We're using async calls, just replaced DOH to SimpleResolver.

**Comment by ibauersachs** [comment]
Okay, so where is `child process died` coming from? Did the JVM crash? Was there an OOM situation? Such an EOFException is AFAIK only thrown then the NIO selector is being closed, which only happens in a JVM shutdown hook.

**Comment by ibauersachs** [comment]
Somewhere earlier in your logs, is there a message `No available source port found`? This is what I get if I run too many queries in parallel, followed by `Client is closing` because the JVM is shutting down.

**Comment by devrivne** [comment]
I'll check logs for smth like this "No available source port found".

**Comment by devrivne** [comment]
I'm generating a huge continuous load from a trusted network.

пт, 18 сент. 2020 г. в 19:06, Ingo Bauersachs <notifications@github.com>:

**Comment by ibauersachs** [comment]
Not enough feedback.
