### ISSUE TITLE
org.xbill.DNS.Zone should not implement Serializable

### ISSUE THREAD

**Issue by patrick1024** [dnsjava/dnsjava#132]
`org.xbill.DNS.Record` of Branch master and 3.x does not implement `Serializable`. As a result `org.xbill.DNS.Zone` isn't serializable though it implements `Serializable`.

Note: `org.xbill.DNS.Record` of Branch 2.x does implement `Serializable`.

**Comment by ibauersachs** [comment]
The `Serializable` marker of `Record` was deliberately removed in 3.x as there already two well-known serialization formats: DNS. See #114.
`Zone` should not be serializable either anymore, this is an oversight and will be fixed in 4.x.

**Comment by cobalt12345** [comment]
I believe, you have a strong reason to change the interface contract. But we had been using this library for years. Instead of "reinventing the wheel" and creation of our own DTOs, we've used library classes. Our application is a classical distributed enterprise application with tens of services and different communication ways including EJB and SOA web services. And now we have to re-design all those interfaces.

**Comment by patrick1024** [comment]
> I believe, you have a strong reason to change the interface contract. But we had been using this library for years. Instead of "reinventing the wheel" and creation of our own DTOs, we've used library classes. Our application is a classical distributed enterprise application with tens of services and different communication ways including EJB and SOA web services. And now we have to re-design all those interfaces.

We had the same conditions and solved the problem by implementing an own serialisation/deserialisation with `readObject`/`writeObject` methods in the DTO that holds the Zone. The serialisation simply uses the `toMasterFile` method of the `Zone` object.

**Comment by cobalt12345** [comment]
Thanks for hint! I was also thinking about special methods in Java serialization mechanism. Anyway, it requires much efforts - find all usages (and we can detect them only at runtime), change method signatures in all services. Afterwards, we'll have to do the regression.

**Comment by ibauersachs** [comment]
I'll think of re-adding `Serializable` to `Record`. I did not consider the case for short-term serialization within EJBs for remoting. 

Note however that I will definitely not be adding `serialVersionUID` constants again. Those were unmainainted and violated the contract of `Serializable`. Also, now that custom `Record` classes can be defined, there is no guarantee that derived classes don't contain sub- or related classes for e.g. options which might not implement `Serializable`.

What other dnsjava classes do you use within those EJBs?

**Comment by cobalt12345** [comment]
We use org.xbill.DNS.Zone, org.xbill.DNS.Record and all concrete resource records sub-classes. Library classes are not used for lon-term serialization.

**Comment by cobalt12345** [comment]
Hi! Did you add a Serializable?

**Comment by ibauersachs** [comment]
@cobalt12345, @patrick1024 and @ironluca can you please verify if the solution from #242 works for you?

**Comment by patrick1024** [comment]
@ibauersachs since we implemented the workaround I described above there is no need (and time) at the moment to verify it. But I'll verify it as soon as there is some spare time. Thank you very much.
