### ISSUE TITLE
CNAME alias should return name

### ISSUE THREAD

**Issue by michalsvec** [dnsjava/dnsjava#136]
I think org.xbill.DNS.CNAMERecord#getAlias should return getName() instead of getSingleName(). 

Is that correct? I can open PR once confirmed. 

https://github.com/dnsjava/dnsjava/blob/1d0577c604fe71b3ca4cc36f19c459cbc4eb134b/src/main/java/org/xbill/DNS/CNAMERecord.java#L30-L32

**Comment by ibauersachs** [comment]
Yes, but this method is redundant and confusing, `getName` is sufficient to get the name.

If you create a PR, please add an `@Deprecated` annotation and Javadoc deprecation remark to use `getName` instead. The same mistake is also in `DNAMERecord` and I need to verify `NSRecord`.
