### ISSUE TITLE
3.3.1 timeline?

### ISSUE THREAD

**Issue by aaylward** [dnsjava/dnsjava#138]
Hi @ibauersachs 

Do you have a feeling for when we can expect a 3.3.1 release with the https fix?

Thanks!

**Comment by aaylward** [comment]
thanks @ibauersachs !

**Comment by aaylward** [comment]
@ibauersachs it looks like the release build was cancelled https://travis-ci.org/github/dnsjava/dnsjava/builds/739739880 -- would you mind kicking it off again?

**Comment by ibauersachs** [comment]
The Travis job is only for code coverage reporting. The binaries are available on Maven Central:
https://search.maven.org/artifact/dnsjava/dnsjava/3.3.1/bundle
