### ISSUE TITLE
ExtendedResolver should be able to follow resolv.conf servers order.

### ISSUE THREAD

**Issue by lucclaes** [dnsjava/dnsjava#139]
Currently, ExtendedResolver, by default, uses either a round-robin servers dispatching or a randomized dispatching against servers with fewest errors (If I understand it correctly).
If using servers defined in resolv.conf, we are not able to meet the algorithm that file expects. From the resolv.conf man page:

_"If there are multiple servers, the resolver library queries them **in the order listed**."_

Should it be possible to add an option in order to meet resolv.conf requirements ?

**Comment by ibauersachs** [comment]
The servers should be queried in order if you call `ExtendedResolver.setLoadBalance(false)`. Is this not working as expected?

**Comment by lucclaes** [comment]
'loadbalance' is false by default. Resolvers are sorted as follows, by default:

Collections.shuffle(resolvers);
resolvers = resolvers.stream().sorted(Comparator.comparingInt(re -> re.failures.get())).collect(Collectors.toList());

What I expect is no sort at all...

**Comment by ibauersachs** [comment]
Yes, right, I somehow remembered that load balance was the defaut.
Anyway, if the failures were ignored, i.e. the servers not sorted at all, then what's the point of having multiple resolvers at all? Say the first server in resolv.conf is down, I wouldn't want to wait 5s for every request.
