### ISSUE TITLE
Usage of removed JDK API

### ISSUE THREAD

**Issue by MatanSabag** [dnsjava/dnsjava#140]
In a migration process from Java 8 to 11, I executed `jdeps` on my code and noticed that this code uses JDK removed internal APIs.

```
dns-2.1.5.jar -> JDK removed internal API
   org.xbill.DNS.spi.DNSJavaNameServiceDescriptor     -> sun.net.spi.nameservice.NameService                JDK internal API (JDK removed internal API)
   org.xbill.DNS.spi.DNSJavaNameServiceDescriptor     -> sun.net.spi.nameservice.NameServiceDescriptor      JDK internal API (JDK removed internal API)
```

I searched this repository and noticed that this code still exists in the codebase.
Is there any plan to make this repository to JDK9+ safe?

**Comment by ibauersachs** [comment]
You analysis is against the very old version 2.1.5, current is 3.3.1.

The mentioned classes are only used when you specify dnsjava as the DNS SPI. This is no longer possible on Java 9+ as the SPI was removed, hence the classes aren't even loaded. If you compile dnsjava with a Java 9+ JDK, the classes are excluded. 

All this is already mentioned in the README. There is nothing "unsafe" here.

**Comment by AlanBateman** [comment]
[JEP 418](https://openjdk.org/jeps/418) defines a standard service-provider interface for host name and address resolution. I assume dnsjava should implement a provider if it wants to be used for lookup with the InetAddress API.

**Comment by ibauersachs** [comment]
@AlanBateman  I'm working on it, see #290.
