### ISSUE TITLE
Didn't find class "java.time.Duration" on Android 7.0

### ISSUE THREAD

**Issue by lxygithub** [dnsjava/dnsjava#143]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread. Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.kekenet.baby-1/base.apk", dex file "/data/app/com.kekenet.baby-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kekenet.baby-1/lib/arm, /data/app/com.kekenet.baby-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:4)

**Comment by ibauersachs** [comment]
dnsjava requires Java 8. I don't know enough about Android when that was introduced. Have a look if https://developer.android.com/studio/write/java8-support-table helps.
