### ISSUE TITLE
Suggestion: add more information to unknown host exceptions

### ISSUE THREAD

**Issue by jschewebbn** [dnsjava/dnsjava#149]
I see that there is additional information in the `Lookup` class about why a lookup failed. Adding that information to the message of the unknown host exception may be useful for those trying to debug DNS issues.

A suggestion is here:
```
final String message = String.format("Unknown host: %s result: %d error string: %s", name,
                        lookup.getResult(), lookup.getErrorString());
throw new UnknownHostException(message);
```

**Comment by ibauersachs** [comment]
Which caller of `Lookup` are you referring to? `Address.getByName` and `Address.getAllByName`?

**Comment by jschewebbn** [comment]
To be clear here is the line where the exception is thrown https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/Address.java#L270
