### ISSUE TITLE
Suggestion: make iteration limit a parameter

### ISSUE THREAD

**Issue by jschewebbn** [dnsjava/dnsjava#150]
In previous versions of dnsjava the iteration limit was hardcoded to be 6. Now I see that it's 10 in https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/Lookup.java#L449

It would be convenient if this were a parameter that could be configured for particular uses. I am doing some research that is using DNS with very long CNAME chains and am running into this limit.

**Comment by ibauersachs** [comment]
10 CNAMEs as it is now really is excessive given that the RFC explicitly discourages setting up CNAMEs to CNAME. If you're up for it, you could create a pull request.

**Comment by jschewebbn** [comment]
I agree that 10 is quite excessive and I am probably abusing CNAMEs here. I may put in a pull request.

**Comment by jschewebbn** [comment]
I was recently looking at RFC 1034 and found
"Of course, by the robustness
principle, domain software should not fail when presented with CNAME
chains or loops; CNAME chains should be followed and CNAME loops
signalled as an error."

Given this, rather than having an iteration limit, having a `Set` of `Name` objects that have been visited an only erroring when the same `Name` object is seen a second time.

**Comment by ibauersachs** [comment]
I'm really hesitant on removing the limit entirely, it could easily DoS a client. Do you know how other resolvers and e.g. BIND and Unbound deal with this?

**Comment by jschewebbn** [comment]
I can say that running `host` and `dig` from the command line do not error on these long CNAME chains. I have not dug into their source code to see what the limits are.

What kind of DoS are you thinking would happen? Perhaps a way to address this is to use the `Set` to watch for loops and put a large limit on the size of the `Set` to avoid memory exhaustion. I would also flag that as a separate error from a loop detection, "cname loop" vs. "cname chain too long". The limit on this `Set` could be something like 100 or even 1000 and you'll still be well under any memory limits.

**Comment by jschewebbn** [comment]
I did find this post about BIND https://www.mail-archive.com/dnsop@ietf.org/msg22374.html
It looks like the code checking for 16 lookups is in the file https://github.com/isc-projects/bind9/blob/0d6347b55ea778fa89ca003b257ab086ba1b0214/lib/ns/query.c
