### ISSUE TITLE
Robolectric dependency makes running unit tests in intellij idea fail

### ISSUE THREAD

**Issue by nresare** [dnsjava/dnsjava#152]
I am creating this issue mostly to clarify to others that might run into this problem what is going on. When trying to run any of the unit inside a recent Intellij IDEA (I reproduce this on 2020.3.2 Community Edition) it fails with the somewhat cryptic `TestEngine with ID 'junit-vintage' failed to discover tests`. 

It turns out the reason for this is that the robolectric android-all dependency includes classes in the `junit.framework` module. Intellij [tries to be smart](https://github.com/JetBrains/intellij-community/blob/master/plugins/junit/src/com/intellij/execution/junit/TestObject.java#L335-L347), and if JUnit 5 is configured but the vintage runner is not added when this is encountered it adds vintage-runner to the classpath which breaks test detection.

One way of "solving" this would be to revert to the previous reflection based solution. It would also avoid downloading an 125MiB for a fairly trivial use case, but I can understand if you would be reluctant to take a step backwards in terms of readability and maintainability

**Comment by nresare** [comment]
For reference, here is a ticket opened with Jetbrains: https://youtrack.jetbrains.com/issue/IDEA-260838

**Comment by ibauersachs** [comment]
Thanks! I was just running into this as well and wondered what's going on. The tests run successfully in today's master branch of intellij-community. But maybe I can create some kind of a mock class just for compilation to avoid the entire roboelectric dependency.

**Comment by nresare** [comment]
It turns out that this was fixed in IntelliJ master a few days ago according to this https://youtrack.jetbrains.com/issue/IDEA-259811 and a backport of the fix should land in a released version soon.

**Comment by nresare** [comment]
The Intellij fix is now available in IntelliJ IDEA 2021.1 EAP (Community Edition) Build #IC-211.5538.20, closing this issue
