### ISSUE TITLE
Discussion: query API changes

### ISSUE THREAD

**Issue by nresare** [dnsjava/dnsjava#159]
The main way of executing dns queries in dnsjava currently is through the Lookup interface. Behaviours are configured through static methods that changes static state in the class configuring cache, default resolver and search path. Simultaneously Lookup instances represent queries and once a query is complete, results as well as errors are available by calling getter methods. 

I think it might be time to think about how an improved API would look. These are some thoughts I have:

* Resource management is implicit and kind of hidden. For example a Cache object is created when the first Lookup instance is created, a cache that stays around indefinitely. I am also assuming that there might be persistent network connections that are kept open. I think that having an api that mirrors many different types of client apis that has some sort of long lived session object which is queried that can be closed would be more forward.
* Having instances of a single class both represent a query and it's eventual result makes consuming results less straight forward than it needs to be. I think that having immutable value objects be returned from queries and have exceptions for the non-happy cases is a better way.
* A DNS lookup is an operation that lends itself very well to asynchronous code execution. An async API with completion stages would be neat.

Based on these I would propose the following: 

* Introduce a new long lived entry point for the API that implements `AutoCloseable` and that gets configured with properties.
* Have a query method on that long lived entry point that returns an immutable answer instance. 
* Introduce exceptions for communicating failure modes.
* Have both a synchronous blocking variant of the API and an async variant that returns a Future eventually referring to the response.

These new APIs could live alongside the old API and share the same query logic for a smooth transition.

**Comment by ibauersachs** [comment]
> The main way of executing dns queries in dnsjava currently is through the Lookup interface. Behaviours are configured through static methods that changes static state in the class configuring cache, default resolver and search path. Simultaneously Lookup instances represent queries and once a query is complete, results as well as errors are available by calling getter methods.
> 
> I think it might be time to think about how an improved API would look. These are some thoughts I have:
> 
> * Resource management is implicit and kind of hidden. For example a Cache object is created when the first Lookup instance is created, a cache that stays around indefinitely. I am also assuming that there might be persistent network connections that are kept open. I think that having an api that mirrors many different types of client apis that has some sort of long lived session object which is queried that can be closed would be more forward.

The network connections are held by `Nio(Udp|Tcp)Client`, as well as the selector thread. These are implicitly created by the `SimpleResolver`. The connections are closed by timeout or with a shutdown hook. This isn't ideal, but given that there should only be one selector thread and that I wanted to avoid that clients need to call initialization code, it seemed the most suitable. And I was assuming that there won't be many cases - if any - that `Resolver`s change regularly.

> * Having instances of a single class both represent a query and it's eventual result makes consuming results less straight forward than it needs to be. I think that having immutable value objects be returned from queries and have exceptions for the non-happy cases is a better way.

👍

> * A DNS lookup is an operation that lends itself very well to asynchronous code execution. An async API with completion stages would be neat.

👍

> 
> Based on these I would propose the following:
> 
> * Introduce a new long lived entry point for the API that implements `AutoCloseable` and that gets configured with properties.

Bear in mind that static code analyzers will (incorrectly) yell at you when an `AutoCloseable` isn't wrapped in a try-with-resources or when it's not closed in the same method.

> * Have a query method on that long lived entry point that returns an immutable answer instance.

👍

> * Introduce exceptions for communicating failure modes.

Exceptions should only be used if the result is really exceptional, e.g. when a socket was closed, not when the result of a lookup isn't successful, e.g. because of NXDOMAIN. At least in the synchronous API, in an async API it might be more natural.

> * Have both a synchronous blocking variant of the API and an async variant that returns a Future eventually referring to the response.

👍

> These new APIs could live alongside the old API and share the same query logic for a smooth transition.

Definitely, I don't want to create breaking changes / v4.0 for a while longer if not absolutely necessary.

**Comment by nresare** [comment]
Thank you for all the feedback. I am going to start writing some code to have something more concrete to discuss.

While I agree in principle that exceptions should be for the exceptional stuff, and that especially NXDOMAIN is used to often in normal operation, but it frustrates me to force every user of the API to do a

```java
result = api.query(someQuery);
if result.isSuccessful() {
   dealWithRecords(result.getRecords());
} else {
   dealWithFailures(result);
}
```

even in the case where it would make much more sense to defer the error handling deeper down in the call stack, and where the call could be as easy as `dealWithRecords(api.query(someQuery).getRecords())`

Another, option (pun slightly intended) would be to use `Optional` to make a special case of NXDOMAIN and use the well established idioms for making sure that the case of NXDOMAIN is handled.

That way the casual user could `deal(api.query(someQuery).orElseThrow().getRecords()` and the user that expects a lot of NXDOMAIN responses can deal with it without involving exceptions.

Thoughts?

**Comment by ibauersachs** [comment]
I don't really know what the best way is for the exceptional vs. nxdomain/no results case. Taking your example, an exception isn't any better:
```java
LookupResult result;
try {
   result = api.query(someQuery);
   dealWithRecords(result.getRecords());
} catch(LookupException ex) {
   dealWithFailures(result);
}
```

I've started using `Optional`s in other places, so that could be a way. As you stumbled upon dnsjava during the Spotify times, maybe you remember how dnsjava was used there and how you wished the API looked like. My usages of `Lookup` were from within Jitsi and just some very simple A/AAAA and SRV lookups. The dnssecjava project is implementing a `Resolver`, so there's no interaction with `Lookup` directly.

Maybe you could throw together the API you're imagining (without a real implementation) so we can discuss based on that and see how it "feels".

**Comment by nresare** [comment]
Having experimented with a few variants, I have come up with having an immutable `LookupResult` class that holds the result `List<Record>`. I'm thinking `NXDOMAIN` and `NXRRSET` should be represented by an empty list and an enum holding additional detail for the curious power user.

The `CompletionStage` API kind of forces your hand when it comes to exception propagation. Any exceptions will be returned on `.asCompletableFuture().get()` wrapped in an `ExceutionException`. I am not a big fan of this, but I think that the advantage fo conforming to the patterns established by the JDK outweighs the benefits of making this a bit more elegant.

I would argue that the exception example that you detail above is better than the pattern of always checking return value because errors might be handled someplace else in the code. Essentially you can move the error handling up the call stack which I think is very useful.

Please have a look at the draft PR I just opened for some ideas on how an API could look.

Spotify's frameworks made heavy use of Guava's `ListenableFuture` which is separate but similar to `CompletionStage`. I think that it would have been helpful to have some lifecycle management and configuration via properties like I'm proposing. Such a solution would have integrated well with Apple's java code as well, that was typically built on top of [servicetalk](https://servicetalk.io) with Google Guice tying different components together.

**Comment by ibauersachs** [comment]
@nresare is there still stuff to discuss after the `LookupSession` merge or can we close this?

**Comment by nresare** [comment]
this was indeed resolved
