### ISSUE TITLE
Merge dnssecjava into dnsjava

### ISSUE THREAD

**Issue by ibauersachs** [dnsjava/dnsjava#172]
I was thinking for a while already to merge the DNSSEC resolver implemented in [dnssecjava](https://github.com/ibauersachs/dnssecjava) into dnsjava but wasn't sure this is the right thing to do.

Pros:
- dnssecjava is useless without dnsjava and closely depends on the API
- might proliferate DNSSEC a bit
- large test coverage
- parts of dnssecjava's tests depend on internal/private dnsjava API to achieve coverage

Cons:
- my personal interest
- different project licenses <sup>1</sup>
- change of package for dnssecjava
- jar size increase <sup>2</sup>

**Thoughts?**

<hr/>

1) The original license of dnssecjava was BSD-3-Clause (c) VeriSign. I applied LGPL and later EPL to my work, keeping the BSD-3-Clause notice to stay compliant with it. The test replay files from unbound are also BSD-3-Clause. The only external contributions were very small and by people privately asking for a more liberal license (when it was still LGPL), one from VeriSign. Relicensing it back to BSD-3-Clause is thus possible.
However, it would probably be best to keep a single license on dnsjava, meaning a switch from BSD-2-Clause to BSD-3-Clause (which is adding: `3. The name of the author may not be used to endorse or promote products derived from this software without specific prior written permission.`). I don't think this is an issue.

2) Size comparison:

Project | Compressed | Uncompressed
--- | --- | ---
dnsjava | 395 KiB | 811 KiB
dnssecjava | 51 KiB | 113 KiB
merged (including metadata) | 491 KiB | 923 KiB

**Comment by hyperxpro** [comment]
How about dropping support for `dnssecjava` and adding fresh code in `dnsjava` with the existing license? As far as size is concerned, It's not too much increase.

**Comment by ibauersachs** [comment]
There's a _lot_ of work in dnssecjava, you cannot easily do it from scratch. I couldn't do it anyway since I wrote and know dnssecjava, so it wouldn't be clean-room. It just not worth it.

**Comment by hyperxpro** [comment]
Ah, no. I didn't mean complete build from scratch. We can do a clean import (kind of copy-paste) to `dnsjava`.

**Comment by nresare** [comment]
I think I would be against a merge, but I can be convinced otherwise. It is true that having vanilla dnsjava be more useful to more people is valuable, but re-licensing seems like a large undertaking as I believe it would require explicit consent from every copyright holder.

There is an argument to be made that going from BSD 2 clause to BSD 3 clause is a pretty small change, but I still think that it is important that stewards of other peoples contributions in open source projects are very careful to respect everyone's licensing wishes.

**Comment by maltalex** [comment]
> different project licenses

Shouldn't really be a problem. Dnssecjava has 3 contributors, with yourself being the main one by a large margin. IANAL, but as the author you can probably change the license to whatever you want. If you want to be (extra) safe, get an OK from the other two contributors.

> change of package for dnssecjava

Shouldn't be much of an issue as long as there are no collisions. In the worst case scenario a project would depend on both dnssecjava and dnsjava with integrated dnssec and would have some duplicate classes in different packages.

> jar size increase

Seems negligible to me. But if that's a concern, the projects can be integrated but released as two separate jars, so we'd have `dnsjava` and `dnsjava-dnssec` or something similar.

> my personal interest

That one is really up to you. 


Just my 2 cents..

**Comment by ibauersachs** [comment]
@maltalex Thanks, but the licensing wasn't quite that simple. dnssecjava originates from Verisign, so I cannot simply remove the 3rd clause from the BSD license. However, I got Brian Wellington's consent to add the 3rd clause to dnsjava. This aligns well with dnssecjava, and some files of dnsjava already 3-clause anyway.

The merge is coming in #209 for v3.5.
