### ISSUE TITLE
org.xbill.DNS.Lookup java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by sysmat** [dnsjava/dnsjava#175]
- version
```xml
<dependency>
            <groupId>dnsjava</groupId>
            <artifactId>dnsjava</artifactId>
            <version>3.3.1</version>
</dependency>
```
- snippet
```java
Name domainName = new Name(domain);
Lookup soaLookup = new Lookup(domainName, org.xbill.DNS.Type.SOA);
ExtendedResolver authoritative = new ExtendedResolver(new String[]{});
soaLookup.setResolver(authoritative);
soaLookup.setCredibility(Credibility.AUTH_ANSWER);
Record[] soaRecordsDns = soaLookup.run(); // java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```
- stack:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.xbill.DNS.ExtendedResolver$Resolution.send(ExtendedResolver.java:67)
	at org.xbill.DNS.ExtendedResolver$Resolution.startAsync(ExtendedResolver.java:84)
	at org.xbill.DNS.ExtendedResolver$Resolution.access$800(ExtendedResolver.java:31)
	at org.xbill.DNS.ExtendedResolver.sendAsync(ExtendedResolver.java:294)
	at org.xbill.DNS.Resolver.send(Resolver.java:146)
	at org.xbill.DNS.Lookup.lookup(Lookup.java:524)
	at org.xbill.DNS.Lookup.resolve(Lookup.java:581)
	at org.xbill.DNS.Lookup.run(Lookup.java:594)

```
- with old version 2.1.8 it works
- conclusion for v. 3.3.1  if it gets an empty array of servers in ExtendedResolver

**Comment by ibauersachs** [comment]
I cannot reproduce this. The `ExtendedResolver` fails in both 2.1.8 and 3.3.1 without a nameserver, which is correct and expected. At best, the constructor should throw an `IllegalArgumentException`.

Why are you passing an explicitly empty list of nameservers?

**Comment by sysmat** [comment]
- because from DB I can get an empty list
- so I unit test with empty list

**Comment by ibauersachs** [comment]
Whatever you're trying to test, it makes no sense. `ExtendedResolver` is expected to fail without an upstream resolver. It is legal to initialize it with an empty list/array, but then a resolver needs to be added with `org.xbill.DNS.ExtendedResolver#addResolver`.

**Comment by sysmat** [comment]
addResolver this doesn't make sense, because of IndexOutOfBoundsException , wro ng handling of array typically bug

**Comment by sysmat** [comment]
- the library's public surface area should be more resilience
- simple unit test should cover this
