### ISSUE TITLE
sometimes lookup.run() result is null on xiaomi device

### ISSUE THREAD

**Issue by candiceatwb** [dnsjava/dnsjava#176]
val lookup = Lookup("xxxxxxxxxxxxx", Type.TXT)
            lookup.setResolver(SimpleResolver())
            lookup.setCache(null)
            if (!lookup.run().isNullOrEmpty()) {
                val records: Array<Record> = lookup.run()
                if (lookup.result === Lookup.SUCCESSFUL) {
                    val builder = StringBuilder()
                    for (record in records) {
                        builder.delete(0, builder.length)
                        val iterator: CharIterator = record.toString().iterator()
                        while (iterator.hasNext()) {
                            builder.append(iterator.next())
                        }
                        val txt = builder.toString()
                        Log.e("TAG", "txt = ${txt}")
                    }
                }
            }else Log.e("TAG", "txt is null")

@nresare what is the reason for this problem?

**Comment by nresare** [comment]
As you can see in the `run()` [javadoc](https://javadoc.io/static/dnsjava/dnsjava/3.3.1/org/xbill/DNS/Lookup.html#run--) the method will return null if there were no records for the query. Looking for any name that does not exist in the dns system will give you a `null` result.
