### ISSUE TITLE
how to download and use it in Android Studio project.

### ISSUE THREAD

**Issue by alejandroaguileraalcalde-ing** [dnsjava/dnsjava#181]
Probably its a simple doubt, but I cant figure out how to use this library in my Android Studio project. I tried to add "implementation 'dnsjava:dnsjava:3.3.1'" on my gradle file, but I got an error: 

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process D:\.....\app\build\intermediates\transforms\desugar\debug\28.jar

Any idea?

**Comment by ibauersachs** [comment]
I'm not proficient with Android development, but dnsjava requires API Level >= 26. Maybe you're on an older version and thus the dexer cannot process dnsjava.

**Comment by alejandroaguileraalcalde-ing** [comment]
I have level 26.  I think I made a mistake when downloading and using it. How should I download this dnsjava from github and add it to my android studio project?

**Comment by ibauersachs** [comment]
You shouldn't download it from GitHub, declare it as a dependency in your Gradle script (it's on Maven Central: https://search.maven.org/artifact/dnsjava/dnsjava/3.3.1/bundle).

**Comment by alejandroaguileraalcalde-ing** [comment]
I tried that and got this:

**Comment by ibauersachs** [comment]
No.
- First of all, don't use bintray. It was and is broken and will no longer be available in a few weeks. Use `mavenCentral()`
- Use the current version of dnsjava, which is 3.3.1
- Declare a dependency with `implementation 'dnsjava:dnsjava:3.3.1'`

If you don't know how to declare a dependecy in your Gradle scripts, then this is the wrong place for support.

**Comment by alejandroaguileraalcalde-ing** [comment]
Ok, I declared a dependency and run my project. I got this issue: 

_com.android.builder.dexing.DexArchiveBuilderException: Failed to process D:\....\app\build\intermediates\transforms\desugar\debug\13.jar_

**This is my build.gradle (:app) file:** 


import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'com.android.application'
//apply plugin: 'maven'


android {
    compileSdkVersion 26
    buildToolsVersion "26.0.3"


    defaultConfig {
        applicationId "edu.uci.calit2.anteatermo"
        minSdkVersion 14
       // targetSdkVersion 22
        targetSdkVersion 26
        versionCode 18
        versionName "0.1.8"
        multiDexEnabled true

    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            applicationIdSuffix ".dev"
        }
    }
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    }




    dexOptions {
        javaMaxHeapSize "2g"
    }


    lintOptions {
        abortOnError false
    }

    useLibrary 'org.apache.http.legacy'
}

allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

dependencies {
    repositories {
        maven {
            url 'https://maven.google.com'
        }
    }

   compile fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'org.tensorflow:tensorflow-android:1.13.1'
    implementation 'com.google.code.gson:gson:2.4'
    //dns

  implementation    'dnsjava:dnsjava:3.3.1'

    //categorias google
    implementation 'org.jsoup:jsoup:1.11.3'
    implementation 'org.jsoup:jsoup:1.8.3'
    // Our own libraries:
    compile project(":antmonitorlib")
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.google.android.gms:play-services:6.1.71'
}

android {
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}

**Comment by alejandroaguileraalcalde-ing** [comment]
This error is due to I use  Java version 8: 

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    }

But if I dont, used it, I cant use the sdnjava library and other error occurs, Any idea?

**Comment by ibauersachs** [comment]
No, and I'm sorry, but this really isn't the right place to ask for help with Android tools.
