### ISSUE TITLE
Java Native Support

### ISSUE THREAD

**Issue by YunaBraska** [dnsjava/dnsjava#182]
Hi I am currently testing java native with Quarkus using GraalVM and get the following stack trace.
It might be the issue with the `SecureRandom`. I have not much knowledge about `SecureRandom` is it really that different than the usual `Random`? Else can you have a look into this? I have no clue how to fix this but would really like to use the library :D Also Spring Boot goes native as well it might be a good time to make this library work on java native :) 

```
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: Object was reached by 
        reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
                constant java.net.InetSocketAddress$InetSocketAddressHolder@4e2cb91a reached by 
        reading field java.net.InetSocketAddress.holder of
                constant java.net.InetSocketAddress@5d76dcb9 reached by 
        reading field org.xbill.DNS.SimpleResolver.address of
                constant org.xbill.DNS.SimpleResolver@ba41067 reached by 
        reading field org.xbill.DNS.ExtendedResolver$ResolverEntry.resolver of
                constant org.xbill.DNS.ExtendedResolver$ResolverEntry@3cefc7af reached by 
        indexing into array
                constant java.lang.Object[]@2c7498c0 reached by 
        reading field java.util.concurrent.CopyOnWriteArrayList.array of
                constant java.util.concurrent.CopyOnWriteArrayList@3105f154 reached by 
        reading field org.xbill.DNS.ExtendedResolver.resolvers of
                constant org.xbill.DNS.ExtendedResolver@27f6e74 reached by 
        reading field org.xbill.DNS.Lookup.defaultResolver
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@2048aa39 reached by 
        scanning method org.xbill.DNS.Header.getID(Header.java:140)
Call path from entry point to org.xbill.DNS.Header.getID(): 
        at org.xbill.DNS.Header.getID(Header.java:140)
        at org.xbill.DNS.Header.toStringWithRcode(Header.java:253)
        at org.xbill.DNS.Message.toString(Message.java:609)
        at java.lang.String.valueOf(String.java:2951)
        at java.io.PrintStream.print(PrintStream.java:745)
        at org.jdom.JDOMException.printStackTrace(JDOMException.java:196)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
```

**Comment by ibauersachs** [comment]
dnsjava really isn't ready for native compilation. There's a lot more static initialization that doesn't work besides the issue with SecureRandom in the `Header` class (reading properties, getting the DNS server addresses, etc.).
Have you read e.g. https://medium.com/graalvm/updates-on-class-initialization-in-graalvm-native-image-generation-c61faca461f7?

For the time being you should be able to use dnsjava with `--initialize-at-run-time=org.xbill.DNS`. You can of course try to narrow that down to more specific classes.

**Comment by MaysonD** [comment]
> dnsjava really isn't ready for native compilation. There's a lot more static initialization that doesn't work besides the issue with SecureRandom in the `Header` class (reading properties, getting the DNS server addresses, etc.). Have you read e.g. https://medium.com/graalvm/updates-on-class-initialization-in-graalvm-native-image-generation-c61faca461f7?
> 
> For the time being you should be able to use dnsjava with `--initialize-at-run-time=org.xbill.DNS`. You can of course try to narrow that down to more specific classes.

Sure , I tried a lot of variants. Got it, thanks
