### ISSUE TITLE
MX Lookup on android return empty for iqdigital.de

### ISSUE THREAD

**Issue by lecanhhiep** [dnsjava/dnsjava#183]
Hi,

Could you please help me fix that issue?
MX lookup on android return empty for iqdigital.de domain.

Below is my code:
```
Record[] records;
//			ResolverConfig.getCurrentConfig().refresh(context);
			Lookup.setDefaultResolver(new SimpleResolver());// change to any others or remove has the same result.
			hostname = "iqdigital.de";
			records = new Lookup(hostname, Type.MX).run();
            if(records != null && records.length != 0) {
                for(int i = 0; i < records.length; ++i) {
                    address.addMX(records[i].getAdditionalName().toString());
                }
                return true;
            }
```

**Comment by lecanhhiep** [comment]
I'm using the latest version (3.3.1), the older version 3.2.3 is also the same

**Comment by ibauersachs** [comment]
Please post the log output of dnsjava at debug level.

I assume you're running this on Android because of the commented line with `refresh(context)`. dnsjava cannot automatically determine the DNS servers on Android and needs that method call OR you need to specify the DNS servers to use manually.

**Comment by lecanhhiep** [comment]
Yeah, it's working now
