### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by amitknx** [dnsjava/dnsjava#185]
Hi,
I am using DNS java to check the name server records for domain and when using on my local machine it is throwing java.net.SocketTimeoutException.
I have checked the mac firewall setting and the firewall is off, still it is throwing the error.
Same code is running fine on aws server.

**Comment by ibauersachs** [comment]
You'll need to be more specific. dnsjava attempts to read the system's dns servers, which are the used in the ResolverConfiguration. Have you verified that this detection is working correctly?
If you manually specified a dns server, is it answering to requests from anywhere? It might have a firewall or configuration to only reply in an AWS network. Check if you can run dig or nslookup against it.

**Comment by amitknx** [comment]
Thanks @ibauersachs for the quick response, 
There is some problem with the VPN i guess, Once I get out of the VPN it starts working. I think may be there is some blocking on VPN.
