### ISSUE TITLE
HOST_NOT_FOUND is being cached indefinitely

### ISSUE THREAD

**Issue by amitknx** [dnsjava/dnsjava#186]
Hi,
I am using dnsjava 3.1 to check the name server records for a domain and found out that
if the domain does not exist it is throwing HOST_NOT_FOUND but even after creating ns records it is still throwing HOST_NOT_FOUND.
What is the default caching ttl in case of HOST_NOT_FOUND?
when I restarted the service it got resolved?

**Comment by ibauersachs** [comment]
First of all, please use the newest version, which is currently 3.3.1. And I cannot quite follow your question. Please attach the full nameserver reply that you think is incorrectly handled, with example code of how you're using dnsjava, the actual outcome and the expected outcome. A good example for such a report is #169.

**Comment by amitknx** [comment]
Sorry for the incomplete explanation
Following is the code I am using:
`public boolean isZoneSetup(Name subDomain) {
        log.info(IS_ZONE_SETUP, subDomain);
        try {
           List<String> nameservers = List.of("8.8.8.8", "8.8.4.4");
            ExtendedResolver resolver = new ExtendedResolver(nameServers.toArray(String[]::new));
            resolver.setRetries(3);
            Lookup domainLookup = new Lookup(subDomain, Type.NS);
            domainLookup.setResolver(resolver);
            Record[] nsRecords = domainLookup.run();
            int lookupResult = domainLookup.getResult();
            switch (lookupResult) {
                case Lookup.SUCCESSFUL:
                    return true;
                case Lookup.TRY_AGAIN:
                    return false;
                case Lookup.HOST_NOT_FOUND:
                    throw new DomainNotFoundInDNSException(context);
                case Lookup.TYPE_NOT_FOUND:
                    throw new DNSRecordNotFoundException(context);
                case Lookup.UNRECOVERABLE:
                    throw new DNSLookupFailedException(context);
                default:
                    if (domainLookup.getErrorString().equals("SERVFAIL")) return false;
                    throw new DNSLookupFailedException(context);
            }
        } catch (UnknownHostException uhe) {
            log.error(uhe)
           throw uhe;
        }
    }`

- Calling first time for subdomain (abc.amitknx.com) with no nameserver records setup:
           Expected: HOST_NOT_FOUND
           Actual: HOST_NOT_FOUND

- Setup nameservers for abc.amitknx.com:
           Expected: SUCCESSFUL
           Actual: HOST_NOT_FOUND even after an hour

- After Restarting service: result SUCCESSFUL

**Comment by ibauersachs** [comment]
Have you checked the TTL of your SOA record(s)? The cache uses this value for the NXDOMAIN results.

Run this example:
```java
SimpleResolver sr = new SimpleResolver("8.8.8.8");
Record q = Record.newRecord(Name.fromString("subdomain.example.com."), Type.NS, DClass.IN);
System.out.println(sr.send(Message.newQuery(q)));
```

It'll give you this
```
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59746
;; flags: qr rd ra ; qd: 1 an: 0 au: 1 ad: 1 
;; QUESTIONS:
;;	subdomain.example.com., type = NS, class = IN

;; ANSWERS:

;; AUTHORITY RECORDS:
example.com.		1533	IN	SOA	ns.icann.org. noc.dns.icann.org. 2021022328 7200 3600 1209600 3600

;; ADDITIONAL RECORDS:
.			0	CLASS512	OPT	 ; payload 512, xrcode 0, version 0, flags 0

;; Message size: 106 bytes
```

The TTL in this example is 1533, which is used for the cache. If you don't want that, limit the cache's expiry time with `setMaxCache(int secods)`. You can either configure the default cache, or set a new instance on your Lookup.

**Comment by amitknx** [comment]
@ibauersachs Thanks for the quick response:
I have explored a bit after your reply following are my findings:

- Response of System.out.println(sr.send(Message.newQuery(q)))
```
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40062
;; flags: qr rd ra ; qd: 1 an: 0 au: 1 ad: 1 
;; QUESTIONS:
;;	abc.example.com., type = NS, class = IN

;; ANSWERS:

;; AUTHORITY RECORDS:
example.com.		899	IN	SOA	ns-194.awsdns-29.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; ADDITIONAL RECORDS:
.			0	CLASS512	OPT	 ; payload 512, xrcode 0, version 0, flags 0

;; Message size: 126 bytes
```

- Cache expiry time is being set  86400 which is the last number in authority section 

- Where as TTL is 899 second

**Comment by ibauersachs** [comment]
Well, the code is not quite correct, but in this case the outcome is. [RFC2308](https://tools.ietf.org/html/rfc2308), Section 3 says:
> The TTL of this record is set from the minimum of the MINIMUM field of the SOA record and the TTL of the SOA itself, and indicates how long a resolver may cache the negative answer.

So, 899 is correct since it is smaller than the 86400.

Do you think there's something wrong? Otherwise I don't know what the issue is.
