### ISSUE TITLE
feature request: support for extended DNS errors ( RFC8914 )

### ISSUE THREAD

**Issue by gryphius** [dnsjava/dnsjava#187]
It would be cool if DNSJava supported EDNS Option Code 15, extended DNS errors  ( https://tools.ietf.org/html/rfc8914 ) .  This would allow us to extract details such as "why did the resolver return SERVFAIL" (for example because DNSSEC signatures have expired)

EDE currently provides 24 predefined codes , which would be nice if we could fetch them in both numeric and textual representation( i.e. Code `10` = "RRSIGs Missing"), plus there is also a `EXTRA-TEXT` field which may contain additional textual information provided by the server.

Resolver implementation status:
 - PowerDNS Recursor ( available since 4.5  - https://github.com/PowerDNS/pdns/pull/9673 )
 - Knot ( Work in progress  - https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/794/diffs)
 - Unbound ( planned - https://github.com/NLnetLabs/unbound/issues/345 )
 - BIND ( planned - https://gitlab.isc.org/isc-projects/bind9/-/issues/1836 )

Examples of client Implementations:
 - miekg/dns library ( merged in  https://github.com/miekg/dns/pull/1253 )
 - dig ( not sure when this was added.. but my dig on arch linux shows EDE when querying a powerdns recursor with 8914 enabled:

```
dig @192.168.23.100 -p 5300 dnssec-failed.ch
[...]
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; EDE: 10 (RRSIGs Missing)    <-------------------------
;; QUESTION SECTION:
;dnssec-failed.ch.		IN	A
```

**Comment by ibauersachs** [comment]
Hm, work done twice. But have a look at my PR please, since the enum variant you went for isn't something that works well with the extensibility required by DNS.

**Comment by gryphius** [comment]
wow, that was fast, thanks a lot!

My attempt was more of a exercise for my rusty java skills and can safely be ignored ;-)
( and I see now, the enum was indeed a bad idea)

**Comment by ibauersachs** [comment]
Can you please confirm that this is working as expected? I did not have a resolver implementing this available. You can approve/reject/comment directly in the PR.
