### ISSUE TITLE
Wish the Cache class did not purge expired records

### ISSUE THREAD

**Issue by slisznia** [dnsjava/dnsjava#19]
Currently, the Cache class strictly obeys the TTL and drops expired records. Instead, it would be nice to have this behavior:
* if TTL has not expired, we use the entry.
* if TTL has expired, we query the resolver(s) to refresh it. If query fails, we reuse the most recent record, even if expired. There is a good chance it still has a valid IP; currently the resolution fails entirely and it's the end.

**Comment by ibauersachs** [comment]
From readme:
>*Reporting issues and providing patches to the upstream project*
This should be done using the dnsjava sourceforge project located at http://sourceforge.net/projects/dnsjava/. For your code tracking convenience, the commits to upstream trunk are also available in the branch named upstream.
