### ISSUE TITLE
Zone.findRecords does not follow CNAME

### ISSUE THREAD

**Issue by smsapiro** [dnsjava/dnsjava#196]
Hi, I am having trouble with `Zone.findRecords` not following `CNAME`. According to the [documentation on `Zone.findRecords`](https://javadoc.io/doc/dnsjava/dnsjava/latest/org/xbill/DNS/Zone.html#findRecords-org.xbill.DNS.Name-int-), following `CNAME` should be possible, but please let me know if I'm doing something incorrectly. Example code below:

```
Name zoneName = new Name("example.");
Zone zone = new Zone(zoneName, new Record[] {
  new SOARecord(zoneName, DClass.IN, 3600L, Name.fromString("nameserver."), new Name("hostmaster",zoneName), 1, 21600L, 7200L, 2160000L, 3600L),
  new NSRecord(zoneName, DClass.IN, 300L, Name.fromString("nameserver.")),
  new ARecord(new Name("test", zoneName), DClass.IN, 3600, InetAddress.getByName("1.2.3.4")),
  new CNAMERecord(new Name("cname", zoneName), DClass.IN, 3600, new Name("test", zoneName))
});

Name testName = Name.fromConstantString("cname.example.");

// Looking up the CNAME record
SetResponse resp = zone.findRecords(testName, Type.CNAME);
System.out.println(resp.answers());
// Prints: [{ cname.example. 3600 IN CNAME [test.example.] }]
// This works as expected.

// Following the CNAME to lookup the A record
resp = zone.findRecords(testName, Type.A);
System.out.println(resp.answers());
// Prints: null
// This does not work. I would have expected: [{ test.example. 3600 IN A [1.2.3.4] }]
```

Thanks!

**Comment by ibauersachs** [comment]
Hm, I think in this case the Javadoc is misleading. The `Zone` class does not perform full lookups, but it does return the CNAME when you're asking for the A-type: add `System.out.println(resp.getCNAME());` as the last line of your example and you'll see it.

Have a look at `org.xbill.DNS.tools.jnamed#addAnswer` for an example on how to use the `Zone` and `SetResponse` class.

**Comment by smsapiro** [comment]
Ah I see, thanks for the explanation!
