### ISSUE TITLE
resolving domain name with timeout

### ISSUE THREAD

**Issue by OrangePieiep** [dnsjava/dnsjava#197]
Hi,

I am new to this library and DNS. I hope to use this library to write a program to resolve domain name to ip with timeout. 
this function works but doesn't have timeout.
InetAddress addr = Address.getByName("www.dnsjava.org");
It seems can use SimpleResolver and Lookup as it can set timeout.
Any sample code can do that ?

- Thanks

**Comment by ibauersachs** [comment]
Use `Lookup` and set a custom resolver. You can set the timeout on the `Resolver` instance.
