### ISSUE TITLE
IDN / punycode support

### ISSUE THREAD

**Issue by Kent1** [dnsjava/dnsjava#198]
Hello,

I've recently noticed that when using our dns tool (which uses dnsjava), we always got nxdomain for Internationalized Domain Names. I've seen later that the DNS request contained some unicode characters.

Is it by design that domains are not translated to the ASCII version or am i using the API wrongly perhaps ?

Thanks,
Quentin

**Comment by ibauersachs** [comment]
Well, I guess you could call it by design, but it's more like nobody has yet gotten around to implement IDN translation in the `Name` class.

**Comment by Kent1** [comment]
Ok, i'll make a pull request in that case :) Seems fairly easy, will look at your codebase.

**Comment by Kent1** [comment]
I must say i am a bit confused by all the code in Name. Here some questions:

My POV is that the Punycode conversion could happen during the toString() call. However, looping over byte[] is not really best to apply the IDN algorithm. Is there a reason to story byte[] instead of String ?
However, doing the conversion only during toString() is not enough, since we should check length of labels not being greater than 63 when Punycode encoded.

Also, i see that Name escapes non-printable ASCII characters. Should that be replaced (partially) by IDN ? Partially since I also see characters like parenthesis or comma. Are those somewhere supported in domain names ?

Quentin

**Comment by ibauersachs** [comment]
> I must say i am a bit confused by all the code in Name. Here some questions:
> 
> My POV is that the Punycode conversion could happen during the toString() call. However, looping over byte[] is not really best to apply the IDN algorithm. Is there a reason to story byte[] instead of String ?

The Name class is a representation of the DNS name, which is essentially a binary format. Storing it as such is IMO correct.

> However, doing the conversion only during toString() is not enough, since we should check length of labels not being greater than 63 when Punycode encoded.

You'll probably want to convert from e.g. `fenêtre.example.org` to `xn--fentre-kva.example.org` in Name constructor. `toString()` should then return the punycode, while e.g. `toUnicodeString()` (or an overload of `toString()`) could return the unicode string again. Storing the punycode encoded data in Name would definitely fix your NXDOMAIN issues.

> Also, i see that Name escapes non-printable ASCII characters. Should that be replaced (partially) by IDN ? Partially since I also see characters like parenthesis or comma. Are those somewhere supported in domain names ?

Not sure about the invalid characters, I'll need to look at that. AFAIK the Name constructor (or `fromString(...)`) should throw if it encounters invalid input.

**Comment by ibauersachs** [comment]
@Kent1 Please have a look at #207. Does this work for you?

**Comment by Kent1** [comment]
Hey @ibauersachs, sorry for not giving any news, holidays and other projects..
It seems to work ! I don't understand everything in your commit, but i did run some tests and it seems working !

Thanks for handling it.

**Comment by ibauersachs** [comment]
As per the comment in #207, the current code won't stay as it is.

**Comment by ibauersachs** [comment]
I decided to revert the changes. I don't currently see how IDNs could be properly supported in dnsjava. Deciding which IDN version to use for example is not something a library can do, and the lack of IDN2008 in Java would required pulling in e.g. icu4j as a dependency.
You mentioned a tool that uses dnsjava. I think it'd be best if you validate the user input there and convert to whichever IDN version you want before passing the (converted) domain name to dnsjava.
