### ISSUE TITLE
3.4.1 release?

### ISSUE THREAD

**Issue by aaylward** [dnsjava/dnsjava#203]
Hi @ibauersachs,

I'm excited to see the update to SVCB/HTTPS records! Is there a schedule for a 3.4.1 release?

**Comment by ibauersachs** [comment]
No, there isn't. The change was merely a rename, do you urgently need to parse SVCB from strings with the new name? Also, there are always snapshots available.

**Comment by aaylward** [comment]
we'd like to get the change in sooner than later to avoid incorrectly validating these names since it's much easier to keep bad data out of a system than it is to clean up after it's in :)

Are there any other issues you want to get into 3.4.1? If not, would you mind cutting a release?

**Comment by ibauersachs** [comment]
Released in 018b45f5b2d49612c607e46d64f5744ca28e6a91.

**Comment by aaylward** [comment]
Thanks @ibauersachs !
