### ISSUE TITLE
Behavior of ExtendedResolver.setTimeout

### ISSUE THREAD

**Issue by lucasXing24** [dnsjava/dnsjava#206]
Hi, 

I am trying to resolve domain names to ip with timeout. I set the timeout in resolver, however, looks like the timeout be ignored?
I tried many times, the time elapsed measured is around 50 ms on my setup.
Looks like it ignore the resolver timeout ? Is there anything wrong with my code?

```java
import org.xbill.DNS.*;

public class eee {
    public static void main(String[] args) {

        Resolver r1 = null;
        try {
            String [] resolvers = new String [] {
                    "1.1.1.1",
                    "8.8.8.8",
                    "8.8.4.4"
            };
            r1 = new ExtendedResolver(resolvers);
            r1.setTimeout(0, 20);
        } catch (Exception e) {}

        Lookup l = null;
        org.xbill.DNS.Record[] records = null;

        String s = "github.com";
        try {
            l = new Lookup(s);
            l.setResolver(r1);
        } catch (Exception e) {}

        long start = System.currentTimeMillis();

        try {
            records = l.run();
        } catch (Exception e) {}

        System.out.println(System.currentTimeMillis()-start);
        String ip;
        if (records != null && records.length != 0) {
            String[] ans = records[0].toString().split("\t");
            ip = ans[ans.length - 1];
            System.out.println(ip);
        }
    }
}
```

output:
54
192.30.255.113

**Comment by ibauersachs** [comment]
What version of dnsjava are you using and why do use use the deprecated method to set the timeout?

**Comment by lucasXing24** [comment]
Thanks @ibauersachs, I updated the version to
    <dependency>
      <groupId>dnsjava</groupId>
      <artifactId>dnsjava</artifactId>
      <version>3.4.1</version>
    </dependency>
  </dependencies>

and use some new API for timeout. Still not working.. Looks like the timeout is ignored also 

import org.xbill.DNS.*;

import java.time.Duration;

public class eee {
    public static void main(String[] args) {
        Duration duration = Duration.ofMillis(20);
        Resolver r1 = null;
        try {
            String [] resolvers = new String [] {
                    "1.1.1.1",
                    "8.8.8.8",
                    "8.8.4.4"
            };
            r1 = new ExtendedResolver(resolvers);
            r1.setTimeout(duration);
        } catch (Exception e) {}


        Lookup l = null;
        org.xbill.DNS.Record[] records = null;

        String s = "github.com";
        try {
            l = new Lookup(s);
            l.setResolver(r1);
        } catch (Exception e) {}

        long start = System.currentTimeMillis();

        try {
            records = l.run();
        } catch (Exception e) {}

        System.out.println(System.currentTimeMillis()-start);
        String ip;
        if (records != null && records.length != 0) {
            String[] ans = records[0].toString().split("\t");
            ip = ans[ans.length - 1];
            System.out.println(ip);
        }
    }
}

**Comment by lucasXing24** [comment]
@ibauersachs , Can you reproduce this issue in your setup ? Is there anything wrong with my code?

**Comment by ibauersachs** [comment]
The timeout only applies to the resolver, not the entire lookup. Try running the resolver only, with something like this:

```java
import org.xbill.DNS.*;

import java.io.IOException;
import java.time.Duration;
import java.util.concurrent.TimeUnit;

public class ResolverTimeoutTest {
  public static void main(String[] args) throws IOException {
    SimpleResolver[] resolvers =
        new SimpleResolver[] {
          new SimpleResolver("1.1.1.1"),
          new SimpleResolver("8.8.8.8"),
          new SimpleResolver("8.8.4.4"),
        };
    for (SimpleResolver r : resolvers){
      r.setTimeout(Duration.ofMillis(1));
    }
    Resolver r1 = new ExtendedResolver(resolvers);
    r1.setTimeout(Duration.ofMillis(1));
    for (int i = 0; i < 10; i++) {
      long start = System.nanoTime();
      Object r;
      try {
        Message response =
            r1.sendAsync(
                    Message.newQuery(
                        Record.newRecord(
                            Name.fromConstantString("github.com."), Type.A, DClass.IN)))
                .toCompletableFuture()
                .get();
        r = Rcode.string(response.getHeader().getRcode());
      } catch (Exception ex) {
        r = ex;
      }
      System.out.println(TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start) + ": " + r);
    }
  }
}
```

But then it's still more complicated:
- The first lookup is always slow: the NIO thread must be started and this will not count against the timeout
- The timeout _only_ applies to the `ExtendedResolver`, not the individual resolvers it consists of (specified by the three IP addresses). If the ExtendedResolver's timeout has expired, it simply doesn't send any further queries to the inner resolvers.
- 20ms, as in your example, is a ridiculously low timeout. You can only reasonably set this to something in the low seconds.
- Additionally, timeouts of the SimpleResolver are only processed with a resolution of 1 second. Everything faster than that won't get you a timeout. If that were much more often, it would essentially result in a busy wait.
  https://github.com/dnsjava/dnsjava/blob/9a317695ac52efeead68d4e3d6d9d3fd9c83c87e/src/main/java/org/xbill/DNS/NioClient.java#L110-L127

I'll try to clarify the Javadoc on `org.xbill.DNS.ExtendedResolver#setTimeout` and I could consider making the 1s period for timeout processing configurable if you absolutely require that.

**Comment by lucasXing24** [comment]
Hi @ibauersachs , 

Thanks for replying and give these examples. 

I run your code looks like the timeout is 1 second. As you mentioned, SimpleResolver are only processed with a resolution of 1 second. Could you make it configurable with a resolution of 1 million second?

Thanks

**Comment by ibauersachs** [comment]
I guess you mean 1 microsecond, not ~11.5 days. Anyway, no.
- No OS has such a low timer resolution, e.g. on Windows you usually have 14-16ms
- This would essentially create a busy loop

Keep in mind that 1 microsecond means that at light speed (under theoretical/ideal conditions) you'd get as far as 300 meters. 

What _exactly_ are you trying to solve?

**Comment by lucasXing24** [comment]
Hi @ibauersachs ,

Sorry, there is typo in my last post. I mean a resolution of 1 millisecond. Is that doable? I plan to use the library in a streaming pipeline. The traffic is huge so I have to give up the resolving process if it takes too long. Otherwise the whole pipeline throughput drops. 

Thanks

**Comment by lucasXing24** [comment]
looks like set the two timeout. The timeout behavior is expected.

        if (r == null){
            SimpleResolver[] resolvers =
                    new SimpleResolver[] {
                            new SimpleResolver("1.1.1.1"),
                            new SimpleResolver("8.8.8.8"),
                            new SimpleResolver("8.8.4.4"),
                    };
            for (SimpleResolver r : resolvers){
                r.setTimeout(Duration.ofMillis(40));
            }
            r = new ExtendedResolver(resolvers);
            r.setTimeout(Duration.ofMillis(40));
        }

I think we can close this Thanks @ibauersachs
