### ISSUE TITLE
update cname record issue

### ISSUE THREAD

**Issue by eilon-shai** [dnsjava/dnsjava#208]
I am trying to add CNAME record with:

Name zoneName = Name.fromString("example.com");
Update update = new Update(zoneName);
update.add("a", 5, 600, "123.abc.com");

but instead of get:

a.example.com.	600	IN	CNAME	123.abc.com

I am getting

a.example.com.	600	IN	CNAME	123.abc.com.example.com.

I have noticed that the CNAMERecord doesnt implement the rdataFromString method and use the SingleNameBase
implementation that concat the value with the origin, is it on purpose? 

am I doing it wrong?

**Comment by ibauersachs** [comment]
You're updating with a relative name. Make it absolute and it should work as expected.

**Comment by eilon-shai** [comment]
Hi, 

thank you for your answer,

this is what I am doing, I mistakenly put it wrong, it is:

Name zoneName = Name.fromString("example.com");
Update update = new Update(zoneName);
update.add("a.example.com", 5, 600, "123.abc.com");

I found the issue, I am working on test env and the zone abc.com was missing, after adding it
it work as expected.


Thanks
