### ISSUE TITLE
TCPClient incorrect receive timeout

### ISSUE THREAD

**Issue by nguydavi** [dnsjava/dnsjava#218]
Hi,

I noticed that the TCPClient uses `endTime` as nanoseconds but this line still compares it with `currentTimeMillis`
https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/TCPClient.java#L115. This essentially makes the receive timeout being ignored.

This was introduced in https://github.com/dnsjava/dnsjava/commit/629f2eb3f5c5ff0695f8264dde03ed7666744775, and I don't know if there are other similar bugs in the other files that were changed.

Thanks!

**Comment by ivanr** [comment]
We're running into this issue a lot in production. Are there any plans to make a new release that will include the fix? Thanks.

**Comment by ibauersachs** [comment]
@ivanr I missed that this was only fixed in master and not in the 3.4.x branch. It would need a backport for a release, 3.5 (i.e. master) won't happen anymore this year.

**Comment by ivanr** [comment]
@ibauersachs Could you please reopen this ticket until a fix is released?
