### ISSUE TITLE
dnsjava 3.4.2 causing Nexus scan report "License-Threat Not Assigned"

### ISSUE THREAD

**Issue by xyang7421** [dnsjava/dnsjava#222]
Hi,
After upgrade to the latest dnsjava 3.4.2, our Nexus scan is reporting following license related issue (not presented in 3.4.1)
Policy/Action: License-Threat Not Assigned
Constraint Name: License threat has not been assigned
Conditions:Found licenses that are not assigned to any license threat group ('Non-Standard') Did not find 'Not Supported' license

Not sure if this could be fixed by dnsjava side.

Thanks,
Xu

**Comment by ibauersachs** [comment]
Are you sure this isn't from some misconfiguration on the IQ server?
The only thing that changed in dnsjava from 3.4.1 to 3.4.2 is the link to the license file in the pom.xml (pointing to the correct branch instead of master).

But: dnsjava 3.5 (the master branch) has changed from BSD-2-Clause to BSD-3-Clause to correct some previously mislabeled unit test files. Maybe the IQ server notices the difference on GitHub with what is in the library manifest. I don't think is likely though.

Do you have any insights or other information how IQ comes to the current conclusion.

**Comment by xyang7421** [comment]
I have the same IQ server, just changed the dnsjava version, back and force, 3.4.1 does not complain, 3.4.2 does. 
then only extra info I got from the report is below, I also got a 3.4.1 report for comparison 

Selected Version: | 3.4.2
-- | --
Type: | maven
Group: | dnsjava
Artifact: | dnsjava
Version: | 3.4.2
Declared License: | BSD-2-Clause,Non-Standard
Observed License: | ISC
Effective License: | BSD-2-Clause,ISC,Non-Standard
Highest Policy Threat: | 7 within 2 policies
Highest CVSS Score: | NA
Integrity Rating: | Not Applicable
Cataloged: | 15 days ago
Match State: | exact
Identification Source: | Sonatype
Category: | Networking Utilities


and the 3.4.1 has the following:
Selected Version: | 3.4.1
-- | --
Type: | maven
Group: | dnsjava
Artifact: | dnsjava
Version: | 3.4.1
Declared License: | BSD-2-Clause
Observed License: | ISC
Effective License: | BSD-2-Clause,ISC
Highest Policy Threat: | 1 within 2 policies
Highest CVSS Score: | NA
Integrity Rating: | Not Applicable
Cataloged: | 2 months ago
Match State: | exact
Identification Source: | Sonatype
Category: | Networking Utilities

**Comment by ibauersachs** [comment]
It's correctly detecting two files which are additionally ISC licensed (`Tokenizer.java` and `ZoneTransferIn.java`), but I really don't know what IQ detects as non-standard, especially since it thinks this is "declared". Have a look at the diff here:
https://github.com/dnsjava/dnsjava/compare/v3.4.1..v3.4.2

The only idea I could imagine are the examples.

**Comment by xyang7421** [comment]
May be we should see if 3.5 fixed it?

**Comment by ibauersachs** [comment]
I'd be curious what the output of that report is if you use `3.5.0-SNAPSHOT`.

**Comment by xyang7421** [comment]
Can I pull it now? I can try.

**Comment by ibauersachs** [comment]
It's on Maven Central snapshots. You might need to enable the repository, see e.g. here: https://stackoverflow.com/a/7717234

**Comment by xyang7421** [comment]
well, it did not show any violation, but I guess it is not conclusive as it says "Not provided" lol. I can wait for the official release is out and see how that goes.
Thanks,
Xu

Selected Version: | 3.5.0-SNAPSHOT
-- | --
Type: | maven
Group: | dnsjava
Artifact: | dnsjava
Version: | 3.5.0-SNAPSHOT
Declared License: | Not Provided
Observed License: | Not Provided
Effective License: | Not Provided
Highest Policy Threat: | NA
Highest CVSS Score: | NA
Cataloged: | -
Match State: | exact
Identification Source: | Package Manifest
Category: | Other

**Comment by ibauersachs** [comment]
Well, this is weird. Maybe you need to configure a policy for snapshot artifacts? If you're on a paid plan for IQ server, maybe you can raise a ticket with Sonatype. Once a release is out I can't change it anymore.

**Comment by xyang7421** [comment]
I am sure our company paid for them, but I have not control on the policy configuration.  is 3.5.0 coming out soon?

**Comment by ibauersachs** [comment]
No, that will take a while. Definitely not October.

**Comment by xyang7421** [comment]
I see. No worry. not a showstopper. only our security guys screaming. feel free to close it, or if you don't mind to keep it open until we got the final fix. Up to you.
Thanks for your help.
Xu

**Comment by ibauersachs** [comment]
If you're following up internally or with Sonatype we can leave it open, otherwise there isn't much I can do.

**Comment by xyang7421** [comment]
sure, I will close it for now, will contact if can't get over it later.
