### ISSUE TITLE
Facing issue while resolving fqdn in kubernetes cluster environment using dnsjava.

### ISSUE THREAD

**Issue by ajithgg** [dnsjava/dnsjava#233]
Java version: 17
dnsjava version: 3.2.2

**Issue :**
We are using dnsjava to resolve fqdn from core dns to get its ip,ttl and other details. We are facing issue in kubernetes cluster environment that the dns resolution does not result in any records to the fqdn where as when using normal java stack its able to resolve the fqdn and get us the ip addresses.

When we debugged the issue we found that dnsjava is not considering the searches present in /etc/resolv.conf. 

**Sample code using dnsjava :**
```
Lookup lookup = new Lookup(fqdnName);
Record[] records = lookup.run();
logger.debug("records after resolution :: {}", records);
```

Does not provide any results in k8s cluster.

**Sample code using java:**
`InetAddress.getAllByName(host);`

results in ip addresses in k8s cluster.

The below parameters are returning empty when debugged in dnsjava.
logger.debug("Resolvers in lookup =====> :: ",lookup.getDefaultResolver());
logger.debug("searches in lookup =====> :: ",lookup.getDefaultSearchPath());
logger.debug("ResolverConfig =====> :: ",ResolverConfig.getCurrentConfig().searchPath());

Could you please let us know if we are missing to pass any configuration?

**Comment by ibauersachs** [comment]
> When we debugged the issue we found that dnsjava is not considering the searches present in /etc/resolv.conf.

Yes, that was the case before v3.4. Please update to the current release, which is v3.4.2.

**Comment by ajithgg** [comment]
Hi @ibauersachs 

Thanks for your quick response.

As suggested by you I tried by upgrading dnsjava from 3.2.2 to 3.4.2 and it seems to be not working. 

Below is the resolv.conf file contents of my application pod.
`nameserver 10.96.0.10
search ajith.svc.cluster.local svc.cluster.local cluster.local viper-slave1
options ndots:5`

Attached is the pcap file recorded for your analysis.
[egw-pcap.zip](https://github.com/dnsjava/dnsjava/files/7541032/egw-pcap.zip)

Please let me know if you need more details.

**Comment by ibauersachs** [comment]
I'm quite confused what's going on here. Please
- Post a small example that shows the query you're sending
- Enable debug logging
- The query in the .pcap is for `demoapp.ajit-test.svc`, while the resolv.conf has `ajith.svc.cluster.local`. Isn't that a typo (missing h)?
- The query ending up as `demoapp.ajit-test.svc.` in the pcap makes me think that you're sending this as absolute, while it should try (in order)
  - `demoapp.ajit-test.svc.ajith.svc.cluster.local.`
  - `demoapp.ajit-test.svc.svc.cluster.local.`
  - `demoapp.ajit-test.svc.cluster.local.` (-> which I assume you're expecting a response)
  - `demoapp.ajit-test.svc.viper-slave1.`

I assume your resolv.conf is not actually a single line and it just got mangled while you tried to format it?

**Comment by ajithgg** [comment]
Hi @ibauersachs ,

I was suffixing the . in the end of fqdn at the end while resolving it. 
**example:**
`Lookup lookup = new Lookup("demoapp.ajit-test.svc.");`

Now i removed the . suffixing and it seems to be working and i am getting the expected output in Records.
`Lookup lookup = new Lookup("demoapp.ajit-test.svc");`

Please let me know if this is right and if any issues i might face in future.

**Comment by ibauersachs** [comment]
Search paths are obviously not used if you query for a FQDN.
