### ISSUE TITLE
Switch from using Random to SecureRandom

### ISSUE THREAD

**Issue by ibauersachs** [dnsjava/dnsjava#24]
Switch from using Random to SecureRandom.

Our security team's code scanner flagged an issue where we use Random in Header.java when we should be using SecureRandom.

This project already uses SecureRandom in other places in the code, UDPClient.java.

There is some additional discussion on SecureRandom vs. Random here: https://stackoverflow.com/questions/11051205/difference-between-java-util-random-and-java-security-securerandom

**Comment by ibauersachs** [comment]
https://sourceforge.net/p/dnsjava/bugs/71/

**Comment by bwelling** [comment]
The primary reason why I never accepted this change is that using SecureRandom instead of Random causes problems when replacing the default system resolver with dnsjava on platforms that use DNS lookups when seeding the random number generator. Getting the UDPClient SecureRandom code to not hang any any of the initialization paths was incredibly complicated.

**Comment by ibauersachs** [comment]
> platforms that use DNS lookups when seeding the random number generator

Do you remember which one that is?

The other thing about blocking I think has been solved by Java using /dev/urandom again. At least on Jitsi we don't do any hacks for using SecureRandom anymore. Plus, the system resolver SPI is gone in Java 9+.

**Comment by bwelling** [comment]
At the time, it was Windows in practice, but in reality anything which did not have or could not read /dev/urandom.

There are various workarounds in the code which solved the problem at the time, but I think there was a similar issue a few years later requiring more. 

I’m not sure if this is still an issue, or wat Java does now if it can’t read /dev/urandom.

**Comment by ibauersachs** [comment]
Uh. Windows 9.x maybe? I never encountered an issue on Windows, but I didn't develop much before Vista.

I think we should be able to inject a random generator and defaulting to SecureRandom. Anyone who has issues with that, e.g. on an embedded device, can provide his own. The reason I've migrated this ticket is that it's really related to a security issue (the cache poisoning from 2008).

**Comment by bwelling** [comment]
https://sourceforge.net/p/dnsjava/bugs/34/ Is the thread relating to the last set of changes. That does include Vista, but possibly only in some circumstances.

**Comment by ibauersachs** [comment]
Now it makes sense. Thanks for the pointer!
