### ISSUE TITLE
Time Limit

### ISSUE THREAD

**Issue by zzx769394358** [dnsjava/dnsjava#241]
the dnsjava has provide time limits ？

such as If you don't succeed after 3 seconds, it's a failure.

--- dnsjava.version: 3.4.3

**Comment by ibauersachs** [comment]
I'm not sure I understand your question. You can set a timeout on a resolver, see here:
https://javadoc.io/static/dnsjava/dnsjava/3.4.3/org/xbill/DNS/Resolver.html#setTimeout-java.time.Duration-
