### ISSUE TITLE
dnsjava refuses to create a HTTPS record from a String if at least one parameter is not provided

### ISSUE THREAD

**Issue by ivanr** [dnsjava/dnsjava#243]
The domains youtu.be and youtube.com sometimes return a HTTPS RR that doesn't have any parameters:

```
youtu.be.		213	IN	TYPE65	\# 3 000100
```

dnsjava will accept this, but if an attempt is made to create a HTTPS record from the corresponding textual representation (`1 .`) a TextParseException instance is thrown with message "At least one parameter value must be specified for ServiceMode".

Reading the RFC draft, I couldn't find the place where it's mandated that at least one parameter is required. In fact, the spec is vague about this. However, the wire format definitely allows for no parameters because section 2.2 says: "When the list of SvcParams is non-empty [...]". https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-08

I think the check in dnsjava should be relaxed. The permissive parsing in one place and strict parsing in another creates an issue in our code where we get a RR in wire format, persist it as text (using dnsjava), but can't convert it back into a RR later.

**Comment by ibauersachs** [comment]
@adam-stoler you originally contributed this code, can you please comment on why that restriction was made?

**Comment by adam-stoler** [comment]
@ibauersachs, I agree with the comment from @ivanr.  I also could not find any place where it is mandated that at least one parameter is required.  Furthermore, in the Appendix D Test Vectors, section D.2 lists such a ServiceMode record with no parameters, so this should be allowed.  I must have misinterpreted the RFC draft in my initial implementation.

Additionally, I agree that the asymmetrical behavior between the parsing in text format and wire format is incorrect behavior.  I think simply removing this check in the text parsing code should make the behavior RFC compliant and allow for proper conversions.  I am creating a PR for this change.

**Comment by ibauersachs** [comment]
Merged, thanks for the quick fix!
