### ISSUE TITLE
DDNS update successful but response from DNS server has invalid TSIG

### ISSUE THREAD

**Issue by tomasdang** [dnsjava/dnsjava#248]
I've been trying to upgrade from 2.1.7 to 3.x - tried 3.2.1 and 3.5.0.

After the library update, I've been getting invalid TSIG on what I believe to be the client (dnsjava) side, e.g.:
```
org.xbill.DNS.TSIG - BADSIG: signature verification failed, expected: Ixc3YzjiFwA8jFtWdNUKTg==, actual: hK02lniZl/vNnYxbpmWgHg==
org.xbill.DNS.SimpleResolver - TSIG verify: BADSIG

...

;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id: 36150
;; flags: qr ; qd: 1 an: 0 au: 0 ad: 1 
;; TSIG invalid
;; ZONE:
;;	<zone>, type = SOA, class = IN

;; PREREQUISITES:

;; UPDATE RECORDS:

;; ADDITIONAL RECORDS:
<key>	0	ANY	TSIG	hmac-md5.sig-alg.reg.int. 1645621423 300 16 hK02lniZl/vNnYxbpmWgHg== NOERROR 0
```
On the other hand, named server logs seem to imply the query itself had a correct MAC (`signer <key> approved`)

Initially I thought this to be related to https://github.com/dnsjava/dnsjava/issues/100 - but that issue seems to relate to the query itself having an invalid signature, not the response.

Considering that the updates worked in 2.1.7 - do you perhaps know what could have changed?

**Comment by stanicek** [comment]
It seems, that the `verify` method of `TSIG` class does not receive original request signature which is required for verification of DNS response. The parameter `old` of type `TSIGRecord` is always null in DNS Java 2.1.8+ unlike in 2.1.7 where it contained the signature. 
As the signature is generated by toWire nowadays, it is never part of original message, but the message is still used to extract the signature for verification.

Could you look at it? 

The simplest possible way (not correct for sure), might be using following patch in `SimpleResolver`:
```
Index: src/main/java/org/xbill/DNS/SimpleResolver.java
===================================================================
diff --git a/src/main/java/org/xbill/DNS/SimpleResolver.java b/src/main/java/org/xbill/DNS/SimpleResolver.java
--- a/src/main/java/org/xbill/DNS/SimpleResolver.java	(revision 978a61bca6917700889ce14aeb777884bd6a21d3)
+++ b/src/main/java/org/xbill/DNS/SimpleResolver.java	(date 1645865293281)
@@ -271,7 +271,13 @@
     if (tsig == null) {
       return;
     }
-    int error = tsig.verify(response, b, query.getTSIG());
+    Message signedQuery = null;
+    try {
+      signedQuery = new Message(query.toWire(Message.MAXLENGTH));
+    } catch (IOException e) {
+      throw new IllegalStateException(e);
+    }
+    int error = tsig.verify(response, b, signedQuery.getTSIG());
     log.debug("TSIG verify: {}", Rcode.TSIGstring(error));
   }
 
```

**Comment by ibauersachs** [comment]
Thanks for the report and the investigation.
I'm not sure when I'll find the time to work on it. If you don't mind, a pull request with an unit test would certainly help to speed things up.

**Comment by stanicek** [comment]
@ibauersachs , any idea when this (3.5.1) could be released? Thank you

**Comment by ibauersachs** [comment]
@stanicek Released and available on Maven Central.
