### ISSUE TITLE
DNSSEC DS validate digest length based on digest type

### ISSUE THREAD

**Issue by andrew-boutin** [dnsjava/dnsjava#250]
https://www.iana.org/assignments/ds-rr-types/ds-rr-types.xhtml has a list of the DNSSEC DS digest types. Each has a link to an RFC where it was introduced that details the expected digest length corresponding to the digest type. The dnsjava library DS record validation could validate the digest length depending on the digest type.
* 1 SHA-1 20 bytes.
* 2 SHA-256 32 bytes.
* 3 GOST R 34.11-94 ~~64~~ 32 bytes.
* 4 SHA-384 48 bytes.

**Comment by adam-stoler** [comment]
We also came across this issue recently when using the 3.5.2 version.  I investigated the problem, and saw that the issue has already been fixed in master but has not yet been released.  Is there a release planned soon that will contain this fix?  We would appreciate it.  Thanks!

**Comment by ibauersachs** [comment]
I didn't want to include this in 3.5.x as it introduces a behavior change in the `DSRecord` type. Do you need that behavior specifically or only the validation utilities?

Timeline-wise 3.5.3 will probably happen soonish, but 3.6 still needs a bit more attention with the JPMS changes that I planned for it.

**Comment by adam-stoler** [comment]
Thank you for the quick response.  We would want the behavior change in the DSRecord type, but this is not too urgent.  I agree with your rationale for not wanting to put this behavior change in a minor 3.5.x version.  We can wait to pick this up in the 3.6 version when that is released.  Thanks!
