### ISSUE TITLE
Migration issue from dnsjava 2.1.7 to 3.5.0

### ISSUE THREAD

**Issue by Naadezhda** [dnsjava/dnsjava#251]
When upgrading from dnsjava version 2.1.7 to 3.5.0 almost all asynchronous lookups started to fail with a timeout.

Actually, we make a number of asynchronous lookups, and it seems that they either almost all succeed or almost all timeout after 10 second SilmpleResolver timeout.

After investigation we found that in the older version a separate thread was created for each lookup, while now the lookups are resolved in the ForkJoin common pool, which I guess is occupied by other work and so all lookups timeout.

Could this be the reasons for this behavior?

Also, that's why I tried to override `CompletionStage<Message> sendAsync(Message query)` with custom Executor(**Executors.newFixedThreadPool (10)**), but it didn't help solve this issue (I even think it worsens the behavior).

Will it be possible for you to advise me how we can solve this issue?

**Comment by ibauersachs** [comment]
This seems similar to #211. I don't know how exactly you're creating the lookup and your environment, so what I can suggest is:
- Try to make your code async if possible (use `LookupSession` instead of `Lookup`)
- Make sure you heed the warning of the synchronous `Resolver.send()` method (which is used by `Lookup.run()`): 
  > `The waiting is done on the calling thread. Do not call this method from async code, and especially not from tasks running on {@link ForkJoinPool#commonPool()}, use {@link #sendAsync(Message)} or {@link #sendAsync(Message, Executor)} instead.`

**Comment by Naadezhda** [comment]
Thanks for your suggestions. I really appreciate your help.

Everything is working fine after migrating to async LookupSession and making sure I no longer use {@link ForkJoinPool # commonPool ()} for dns lookups.
