### ISSUE TITLE
DS rdata digest validation hexadecimal digits

### ISSUE THREAD

**Issue by andrew-boutin** [dnsjava/dnsjava#252]
From https://www.rfc-editor.org/rfc/rfc4034.html#section-5.3
> The Digest MUST be represented as a sequence of case-insensitive hexadecimal digits. Whitespace is allowed within the hexadecimal text.

The library allows non hex digits in the digest String. For example this rdata input "1 5 2 2BB18#AF5F22588179A!3B0A98*31FAD1A2^2118" gets normalized to "1 5 2 2BB17FAF5F225881799F3B0A98F31FAD1A1F2118". A digest of "$^" gets converted to "EF".

**Comment by andrew-boutin** [comment]
@ibauersachs per https://github.com/dnsjava/dnsjava/commit/182b5a3039c5be6352a9e5a510b4143a1e7b23cb#diff-f9d43ac9568da097f6fcf1841a792ae3168643498a01ead4a638d4dc5cb65d23R39 it looks like you're ignoring non-hex chars instead of erroring on them. Why allow instead of reject? If a user provides non-hex chars in rdata is it reasonable to suspect that the remaining string after ignoring non-hex chars would be valid / what they intended?

**Comment by ibauersachs** [comment]
The added Javadoc comment in the above commit is wrong. There is a test that asserts a `TextParseException` on invalid characters:

https://github.com/dnsjava/dnsjava/blob/f8c2648c9e2241be5cd51b4ac1e828cca16bb2e6/src/test/java/org/xbill/DNS/DSRecordTest.java#L197-201

**Comment by andrew-boutin** [comment]
@ibauersachs thanks for clarifying. I verified on my end using 3.5.1 as well. Looks good!
