### ISSUE TITLE
Not working on Android 11, throws java.net.PortUnreachableException.

### ISSUE THREAD

**Issue by XXXShaoZi** [dnsjava/dnsjava#261]
Not working on Android 11, throws java.net.PortUnreachableException.

**Comment by XXXShaoZi** [comment]
for MX detect.

**Comment by XXXShaoZi** [comment]
`
        Lookup lookup = new Lookup("gmail.com", Type.MX);
`
`
        Record recs[] = lookup.run();
`
on android 11, recs is null.

**Comment by ibauersachs** [comment]
You need to initialize the Resolver config, see #266 for a similar question.
