### ISSUE TITLE
How to handle ResolverConfig on Android?

### ISSUE THREAD

**Issue by SoccerCodelover28** [dnsjava/dnsjava#266]
For me, It seems not so clear how to approach ResolverConfig on Android. No where in the document explicit on how to handle it.
Is what this person did on stackoverflow would be somewhat the ideal approach?
https://stackoverflow.com/questions/69940334/best-practise-or-example-for-using-alternative-dns-library-on-android-e-g-min

Thank you!

**Comment by ibauersachs** [comment]
Call `org.xbill.DNS.config.AndroidResolverConfigProvider#setContext` in your application before doing any DNS lookups. The [context](https://developer.android.com/reference/android/content/Context) is required to read the DNS server from Android (the system properties `net.dnsX` are not available anymore since API 26).

Example:
```java
public class MyApp extends Application {
  public void onCreate() {
    super.onCreate();
    AndroidResolverConfigProvider.setContext(getApplicationContext());
  }
}
```

But please note the comment on `AndroidResolverConfigProvider`!

> If you are developing for Android, consider implementing your own [ResolverConfigProvider](https://javadoc.io/static/dnsjava/dnsjava/3.5.1/org/xbill/DNS/config/ResolverConfigProvider.html) that listens to network callbacks and properly refreshes on link changes. Something you need to do anyway to call [ResolverConfig.refresh()](https://javadoc.io/static/dnsjava/dnsjava/3.5.1/org/xbill/DNS/ResolverConfig.html#refresh--) otherwise it is pretty much guaranteed to have outdated servers sooner or later.

**Comment by SoccerCodelover28** [comment]
I did similar to this one, #6. I am getting error in it. 
Contents of collection 'listServers' are updated, but never queried
Does the Connectivity Manager be inside of the Lookup?

**Comment by ibauersachs** [comment]
Sorry, I'm having trouble understanding your English and I don't know what exactly you tried.

dnsjava does not contain anything named `listServers`, so I assume this is something you wrote yourself. So what is that? Can you please post the relevant parts of your code?

**Comment by SoccerCodelover28** [comment]
It is okay. I think I figure out the problem.

**Comment by SoccerCodelover28** [comment]
okay I think I am having an error. How do I resolve this,
I/TetheringManager: registerTetheringEventCallback:com.example.
Do I need to have it after this:
 ConnectivityManager connectivityManager = context.getSystemService(ConnectivityManager.class);
Why would I need this if I am doing dns query?

**Comment by ibauersachs** [comment]
I have no idea what you're doing, and I'm not an Android developer. If you're using the built-in dnsjava config provider, you need to initialize it with `org.xbill.DNS.config.AndroidResolverConfigProvider#setContext` before doing anything else with dnsjava.

If you're writing your own `ResolverConfigProvider`, have a look at `org.xbill.DNS.config.AndroidResolverConfigProvider#initialize`. You'll need to register your own provider with `org.xbill.DNS.ResolverConfig#setConfigProviders`.
 
To implement the callbacks as mentioned in the Javadoc of `AndroidResolverConfigProvider`, I'll have to refer you to the Android documentation, e.g. https://developer.android.com/reference/android/net/ConnectivityManager#registerNetworkCallback(android.net.NetworkRequest,%20android.net.ConnectivityManager.NetworkCallback). You can implement the callbacks within your own `ResolverConfigProvider` or somewhere else within your application and then just call `org.xbill.DNS.ResolverConfig#refresh`.
