### ISSUE TITLE
Add KSK in the Flags of DNSKEYRecord

### ISSUE THREAD

**Issue by menglong-github** [dnsjava/dnsjava#270]
It is recommended to add KSK in the Flags of DNSKEYRecord, with a value of 0x101. I support DNSSEC when developing authoritative dns services, and this bit is required

**Comment by ibauersachs** [comment]
I'm not sure what you're referring to.
KSK is a bitmask of the flags 0x100 (for ZONE_KEY) and 0x1 (for SEP_KEY), both of which are defined in DNSKEYRecord.Flags, and you can specify any combination of flag values when reading or creating a DNSKEYRecord.
