### ISSUE TITLE
Package visibility of class EmptyRecord

### ISSUE THREAD

**Issue by FPawlak2** [dnsjava/dnsjava#276]
Hi guys,
I wonder if class 'org.xbill.DNS.EmptyRecord' has specially package visibility instead of public?

As I can see other classes extending 'org.xbill.DNS.Record' class has public visibility. So maybe the keyword 'public' is missing here?

**Comment by ibauersachs** [comment]
`EmptyRecord` is intentionally not public as there is no use for it that I can see. Why do you need it? An instance of it can still be created via e.g. `Record r = Record.newRecord(Name.root, Type.A, DClass.IN, 60)`.
