### ISSUE TITLE
SRV parsing failed

### ISSUE THREAD

**Issue by Wings-Fantasy** [dnsjava/dnsjava#278]
```xml
// pom.xml

<dependency>
    <groupId>dnsjava</groupId>
    <artifactId>dnsjava</artifactId>
    <version>3.5.2</version>
</dependency>
```
<br />

```java
// Test class

Lookup lookup = new Lookup("mc.mod.hxshijie.com", Type.SRV);
//Resolver resolver = new SimpleResolver("8.8.8.8");
//lookup.setResolver(resolver);
Record[] records = lookup.run(); //null
System.out.println(lookup.getResult()); //4
```
<br/>

I have used SRV to resolve this domain name to another domain name, and it works normally. Why is the parsed result empty?

**Comment by ibauersachs** [comment]
There's simply not SRV record at `mc.mod.hxshijie.com`. 4 means TYPE_NOT_FOUND.

**Comment by Wings-Fantasy** [comment]
https://i.328888.xyz/2023/02/09/3YA0d.png

My DNS resolution is fine, and the tcp link of the target server is also online

**Comment by ibauersachs** [comment]
You need to lookup `_minecraft._tcp.mc.mod.hxshijie.com` for that record.

**Comment by Wings-Fantasy** [comment]
This time it was parsed normally. But when we use this DNS, we use `mc.mod.hxshijie.com`, Users don't know what `Service` and `Protocol` are.

**Comment by ibauersachs** [comment]
SRV records are for applications, not humans. If it's always _minecraft._tcp, construct the full name by appending what the users enter. This is how applications typically discover servers addresses. For example, to connect to an XMPP server, users enter `nickname@example.net` and the application looks up the standardized name `_xmpp._tcp.example.net`. Similar for a SIP service `phone-number@calls.example.org` would end in `_sips._tcp.calls.example.org`.

Please read up on SRV records and then possibly reconsider if you really need them.
