### ISSUE TITLE
LookupSession assumes to follow redirects with Type.CNAME

### ISSUE THREAD

**Issue by OrientationZero** [dnsjava/dnsjava#279]
hello,
```
dig www.baidu.com result like this:
www.baidu.com.    IN CNAME www.a.shifen.com.
www.a.shifen.com. IN A          163.177.151.100
www.a.shifen.com. IN A          163.177.151.99
```

my code like this:

```java
        LookupSession look = LookupSession.defaultBuilder().build();
        Name name = Name.fromString("www.baidu.com");
        look.lookupAsync(name, Type.CNAME)
                .thenAccept(f -> System.out.println(f))
                .toCompletableFuture().get();
```
result is :
`LookupResult(records=[], aliases=[www.baidu.com.])`

but I expect CNAME record:
`www.baidu.com.    IN CNAME www.a.shifen.com.`

But using Lookup can do right thing,so what should I do?

**Comment by ibauersachs** [comment]
This is indeed a bug. As a workaround you can use a `Resolver` directly or use the non-async (and thus legacy) `Lookup` class.
