### ISSUE TITLE
Provide Automatic-Module-Name attribute in MANIFEST.MF or add module-info

### ISSUE THREAD

**Issue by kentros** [dnsjava/dnsjava#29]
It would be nice to have an Automatic-Module-Name attribute in MANIFEST.MF.  For more information see this blog:
[Automatic-Module-Name: Calling all Java Library Maintainers](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)

The change should be a one-line addition to the bundle-plugin, adding:

`<Automatic-Module-Name>org.dnsjava</Automatic-Module-Name>`

The only hiccup is what we want that module name to be.  The typical standard is to use the root package name.  In dnsjava's current state that would actually be: `org.xbill.DNS`, so we may want to hold off on this until we've moved to the proposed ideal future package namespace `org.dnsjava` ?

**Comment by ibauersachs** [comment]
Wouldn't it be better if we'd provide a proper module-info? Or did I miss something while reading this blog?

**Comment by kentros** [comment]
Even better.  +1
