### ISSUE TITLE
SimpleResolver fails with a network error on Android when the DNS server is read from the ResolverConfig

### ISSUE THREAD

**Issue by vandac** [dnsjava/dnsjava#291]
When using the SimpleResolver which is supposed to read the host from the ResolverConfig on Android, it uses 'ip6-localhost' as the host. However, it is not possible to query it and always fails with a network error. 
If I read the dns servers from the currently active network using the [ConnectivityManager API](https://developer.android.com/reference/android/net/ConnectivityManager), it works fine. Although the code for [AndroidResolverConfigProvider](https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/config/AndroidResolverConfigProvider.java) looks correctly, the localhost host simply is not satisfactory for making successful DNS queries.

**Comment by ibauersachs** [comment]
Did you initialize AndroidResolverConfigProvider as documented?

I don't own an Android Phone nor am I an Android developer of any sort. Since you're able to query the NetworkManager, can maybe debug whats wrong and provide a PR?
