### ISSUE TITLE
Upgrading SLF4J API to 2.x

### ISSUE THREAD

**Issue by rome-user** [dnsjava/dnsjava#292]
Hello,

Would it be possible to update the SLF4J API dependency to make use of SLF4J 2.0? I am not sure if there are breaking changes that need to be addressed by dnsjava itself, but I am willing to investigate if you do not have the time to do so

**Comment by ibauersachs** [comment]
There are no breaking changes, it's a drop-in replacement. If you need to use dnsjava in a project with slf4j v2 you can do so. Maven and Gradle should both use the newer version if you reference v2 in your project directly.
