### ISSUE TITLE
Generation of key supports insecure keys

### ISSUE THREAD

**Issue by akwick** [dnsjava/dnsjava#293]
## Context

@schlichtig and I manually reviewed randomly sampled JCA usages for a benchmark to identify secure or insecure usages of the API. We considered the usage below as a misuse and labeled it accordingly in our benchmark.

### Description

"Security of the api-call depends on the passed values that may be insecure. It may be that the method is called with the *RSAMD5* or *RSASHA1* algorithm which are insecure.

### Location

- file: dnsjava/src/main/java/org/xbill/DNS/DNSSEC.java
- method: private static PublicKey toRSAPublicKey(byte[] key) throws IOException, GeneralSecurityException
- line: 492 [sampled](https://github.com/dnsjava/dnsjava/blob/55f9cf16608285e4ed9253d7f186530fba0dee33/src/main/java/org/xbill/DNS/DNSSEC.java#L492) [current main branch](https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/DNSSEC.java#L492)

-----
We look forward to your response,  
Anna
for the CamBench team

**Comment by ibauersachs** [comment]
This is intended.
