### ISSUE TITLE
Pushing dnsjava 2.1.7 to Central

### ISSUE THREAD

**Issue by jekh** [dnsjava/dnsjava#3]
It looks like dnsjava 2.1.7 [has just been released](http://www.dnsjava.org/download/README). @noaresare  -- will you be pushing the svn commits to this repo and releasing a new artifact to Central?

**Comment by noaresare** [comment]
Thank you for the heads up. 

I have now pushed all commits up to r1713 from http://svn.code.sf.net/p/dnsjava/code/trunk onto the branch 'upstream', merged into master and bumped pom.xml version to 2.1.7. The resulting artifacts has been uploaded to oss.sonatype.org and should be visible in maven central in an hour or so.
