### ISSUE TITLE
Need for synchronization while looking up Zones

### ISSUE THREAD

**Issue by srijeet0406** [dnsjava/dnsjava#305]
I was wondering what the point of synchronizing methods like `allRRsets`, `oneRRSet`, `lookup` and `exactName` is. Could we possibly use a `ReEntrantReadWriter` Lock (only Read locks in this regard) to attain the same behavior. This should result in considerable performance increase and less resource contention. Any feedback is welcome.

**Comment by ibauersachs** [comment]
This might be possible. The Zone code is rather old and I wonder if might be better to rewrite some parts, especially the ones that use Object to operate on either a single RRSet or on a list of RRSets.

In what case do you run into lock contentions? Multiple parallel reads?

**Comment by srijeet0406** [comment]
@ibauersachs Yes, that Object comparison on RRSet or a list oif RRSets was another one of the areas that I was looking at. But in this case, yes, I'm seeing bottlenecks and resource contentions on the `findRecords` method (which calls the `lookup` method) during multiple reads. I can create a PR for the same if you think it would be helpful.

**Comment by ibauersachs** [comment]
Thanks, a PR is always welcome!
I'm not sure how well the Zone class is test covered, please bear this in mind when refactoring things.

**Comment by srijeet0406** [comment]
@ibauersachs PR is out for review.

**Comment by ibauersachs** [comment]
I refactored much of the Zone class, based on your work in #306, to make it fully thread safe (including the iterator). Hopefully that solves your performance issues. Your PR is closed, but I mentioned you as co-author.
