### ISSUE TITLE
DNSSEC Resolver example is not working

### ISSUE THREAD

**Issue by eilon-shai** [dnsjava/dnsjava#310]
Hi, 

The example of the DNSSEC Resolver that provided in the example section is not working.
the result I get is:

---www.dnssec-failed.org.
AD-Flag: false
RCode:   NOERROR

---www.isc.org.
AD-Flag: false
RCode:   NOERROR

Validating resolver:

---www.dnssec-failed.org.
AD-Flag: false
RCode:   SERVFAIL
Reason:  Could not establish a chain of trust to keys for [dnssec-failed.org.]. Reason: Did not match a DS to a DNSKEY.

---www.isc.org.
AD-Flag: false
RCode:   NOERROR
**Reason:  NSEC3s for the referral proved no DS.**

can you please update with a working example?

Thanks,
Eilon

**Comment by ibauersachs** [comment]
Well, it seems isc.org is no longer signed. Try using another domain that is, e.g. nic.ch.

**Comment by eilon-shai** [comment]
yes it is working, thank you
