### ISSUE TITLE
Full JPMS support

### ISSUE THREAD

**Issue by cowwoc** [dnsjava/dnsjava#311]
Please add a module-info to this project. I know that you have an automatic module name, but this prevents the use of jlink and other nice things that come with `module-info`. You can use a multi-release JAR if you want to maintain Java 8 support.

It's quite easy. Just add:

```
<configuration> 
    <release>9</release> 
    <compileSourceRoots> 
        <compileSourceRoot>${project.basedir}/src/main/java9</compileSourceRoot> 
    </compileSourceRoots> 
    <multiReleaseOutput>true</multiReleaseOutput>
</configuration>
```

to your project and you're done. See https://www.baeldung.com/maven-multi-release-jars for an example.

**Comment by ibauersachs** [comment]
This is already implemented as part of #246.
