### ISSUE TITLE
Add an auto-formatter plugin

### ISSUE THREAD

**Issue by kentros** [dnsjava/dnsjava#32]
> It would be a good idea to enforce the code style through a tool like Checkstyle. Otherwise I would guess that the code formatting could hinder further contributions.

_Originally posted by @SoylentBob in https://github.com/dnsjava/dnsjava/pull/23#issuecomment-493736702_

Adding checkstyle would be good.  It would be even better to add a plugin that just automatically corrects the formatting for us.  If we want to standardize on the google style, we can just add [fmt-maven-plugin](https://github.com/coveo/fmt-maven-plugin) and call it done.  Or alternatively, if you want to define a custom formatting convention, the best bet is probably: [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/examples.html)

**Comment by ibauersachs** [comment]
Yes it would. However, so far the codebase isn't in a consistent style and I'm hesitant to just auto-format everything. Something should and will be done, but I'm just no sure yet how far to go.

**Comment by kentros** [comment]
Checkstyle comes with support for either Google or Sun Java Styles out of the box
* google code convention doc: https://google.github.io/styleguide/javaguide.html
* sun/oracle convention doc: https://www.oracle.com/technetwork/java/codeconvtoc-136057.html 

My preference is the google style.  Oracle doesn't appear to care about updating the code convention docs from Sun anymore.

> I'm hesitant to just auto-format everything

Is there a particular fear you have with an auto-formatting commit?  It shouldn't affect the behavior of the code.

**Comment by ibauersachs** [comment]
> Is there a particular fear you have with an auto-formatting commit?

Losing almost the entire source code history.

**Comment by kingle** [comment]
> Losing almost the entire source code history.

😕 How does applying a formatting change affect the history?

**Comment by ibauersachs** [comment]
Every single line in a blame shows the formatting commit.

**Comment by kentros** [comment]
GitHub now has an improved blame that lets you see previous blames.  https://help.github.com/en/articles/tracking-changes-in-a-file

**Comment by ibauersachs** [comment]
Okay, the format of the unit tests annoys me enough to apply a formatter on the unit test files (only!). Any preferences for the format/code style?

And btw. why do you use two Github accounts? 🤔

**Comment by kingle** [comment]
I got tired of weird messages asking if I was really "Kent Rose", so I switched to use my last name.  Unfortunately, didn't log out of it on all my devices. 🤦

As for style, my preference is Google

**Comment by ibauersachs** [comment]
> I got tired of weird messages asking if I was really "Kent Rose", so I switched to use my last name. Unfortunately, didn't log out of it on all my devices. 🤦

https://help.github.com/en/articles/changing-your-github-username?

> As for style, I don't really care. What plugin are you planning on using? If using formatter-maven-plugin, whatever default it supplies is fine:
> https://code.revelc.net/formatter-maven-plugin/examples.html

Just checkstyle and maybe committing the IntelliJ formatting options.

**Comment by kingle** [comment]
Sounds good
