### ISSUE TITLE
EDNSOption option.getData() method not visible

### ISSUE THREAD

**Issue by svarma-comitfs** [dnsjava/dnsjava#327]
Hi Team,

Hope you are well. 

I am trying to read the option data coming in DNS query. I am able to print option code using getCode() but unable to read option data using getData() method. In EDNSOption class I see that getData() method is defined with default access specifier and hence the method is not visible when I attempted the following code, 

               for (EDNSOption option : opt.getOptions()) {
                        byte[] optionData = option.getData();
                    }

Is there any other way to read option data ?

**Comment by ibauersachs** [comment]
Hi,

The idea is to create derived classes from EDNSOption and parse stuff in there. However, I just realized that the EDNSOption currently doesn't allow to register custom types.

Questions that come to mind:
- Are you missing an option that is specified in an RFC and should become part of dnsjava? Which one(s)?
- Do you really need the raw data?
- Is there a need for an extension mechanism like we introduced in #93 and #94 for `Record`s?
