### ISSUE TITLE
Consider enabling GitHub Pages

### ISSUE THREAD

**Issue by kentros** [dnsjava/dnsjava#33]
It would be nice to also include an easy means of publishing/updating the http://dnsjava.org website.  GitHub Pages seems like a good option:

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

**Comment by kentros** [comment]
Also, it would be great to configure the CNAME so dnsjava.org can still be used.  https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

Free hosting and https

**Comment by ibauersachs** [comment]
I just got hold of dnsjava.org, but I'll probably simply change to redirect here. What content would you like to see on Github Pages?
The list of projects using dnsjava is not something I'll create the pages for, it can be maintained as a file next to the readme.

**Comment by kingle** [comment]
If you just enable it to use master, it will automatically render from the README.md into html.  Here's an example from my fork: https://kentros.github.io/dnsjava/

I'm not opposed to just redirecting the straight to github repo, but having a proper webpage could provide a richer means of providing documentation that already exists (examples, usage, etc.)

**Comment by kingle** [comment]
@bwelling / @ibauersachs can the http://www.xbill.org/dnsjava/ be redirected as well?

**Comment by bwelling** [comment]
It should probably just be removed at this point; dnsjava.org has existed for a long time.

**Comment by ibauersachs** [comment]
Bah, I just tried Github pages and it messed aroud with automatic commits in the master branch. I need more time and repo to play with before I can enable that somewhere safe.
In the meantime I'll simply redirect here as I've already messed with the nameservers.

**Comment by kingle** [comment]
The new redirect works for me -- GitHub pages was just a possible suggestion and may be overkill.  Feel free to close this out.

**Comment by bwelling** [comment]
xbill.org/dnsjava now redirects to dnsjava.org, which (for now) redirects to the top level github page.
