### ISSUE TITLE
dnsjava 3.6.0: DNS responses for secure mode have changed

### ISSUE THREAD

**Issue by pjfanning** [dnsjava/dnsjava#330]
Apologies in advance but I am not an expert on dnsjava. I created a PR to upgrade the lib for Apache Hadoop but some unit tests fail.
https://github.com/apache/hadoop/pull/6961

There is a TestRegistryDNS that still passes but there is a subclass of it called TestSecureRegistryDNS that has test failures.
* [TestSecureRegistryDNS](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-registry/src/test/java/org/apache/hadoop/registry/server/dns/TestSecureRegistryDNS.java)
* The assert in [assertDNSQuery](https://github.com/pjfanning/hadoop/blob/HADOOP-19237-dnsjava/hadoop-common-project/hadoop-registry/src/test/java/org/apache/hadoop/registry/server/dns/TestRegistryDNS.java#L390) expects 2 records in the answer when secure mode is used but with dnsjava 3.6.0, there is just one.
* I think the missing one is expected to have Type.RRSIG
* The test passes with dnsjava 3.5.3

Any pointers would be much appreciated.

PS If you did have time to test this for yourself, you can checkout my PR branch and use this command
```
mvn test -pl :hadoop-registry -am -Dtest="*RegistryDNS*" -Dsurefire.failIfNoSpecifiedTests=false
```

**Comment by ibauersachs** [comment]
Thanks for the report. Can you please add a block here with the contents of `responseBytes` (https://github.com/pjfanning/hadoop/blob/HADOOP-19237-dnsjava/hadoop-common-project/hadoop-registry/src/test/java/org/apache/hadoop/registry/server/dns/TestRegistryDNS.java#L397) as base64 encoded?
It would help a lot to inspect the message and see what's going on without actually setting up Hadoop.

**Comment by pjfanning** [comment]
Thanks @ibauersachs for the quick response.
For one of the broken the tests.

The Base64 encoded responseBytes:
ewSFgAABAAEAAQABJGN0ci1lNTAtMTQ1MTkzMTk1NDMyMi0wMDE2LTAxLTAwMDAwMgNkZXYEdGVzdAAAHAABwAwAHAABAAAAHgAQAAAAAAAAAAAAAP//rBEAE8AxAAIAAQAAAB4ACQd1bmtub3duAAAAKRAAAACAAAAA

The `new Message(responseBytes).toString()` is:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31492
;; flags: qr aa rd ra ; qd: 1 an: 1 au: 1 ad: 1 

;; OPT PSEUDOSECTION: 
; EDNS: version: 0; flags: do ; udp: 4096
;; QUESTIONS:
;;	ctr-e50-1451931954322-0016-01-000002.dev.test., type = AAAA, class = IN

;; ANSWERS:
ctr-e50-1451931954322-0016-01-000002.dev.test.	30	IN	AAAA	::ffff:172.17.0.19

;; AUTHORITY RECORDS:
dev.test.		30	IN	NS	unknown.

;; ADDITIONAL RECORDS:


;; Message size: 123 bytes

**Comment by pjfanning** [comment]
With dnsjava 3.5.3, I get this response.

Base64 encoded:
kXiFgAABAAIAAgABJGN0ci1lNTAtMTQ1MTkzMTk1NDMyMi0wMDE2LTAxLTAwMDAwMgNkZXYEdGVzdAAAHAABwAwAHAABAAAAHgAQAAAAAAAAAAAAAP//rBEAE8AMAC4AAQAAAB4AnAAcCAMAAAAeaIYIR2ak1MehJQNkZXYEdGVzdAB5cw0WUPy7OVtlBgXOnB0PCOrwPDO2guW1IMtYBSoV5GiMiCaZk7T0ae+GS8u3Oh/HV1UThHDA2UcxJhPIO6DJnkQhMdiXC6n3rYAOB/cMvHSXtXPJ3DM0nnAFK6aDcLi0nx5y9l7s3DaS+eDoElDM4cWdC+Q8hMUiMT53lWyT4cAxAAIAAQAAAB4ACQd1bmtub3duAMAxAC4AAQAAAB4AnAACCAIAAAAeaIYIR2ak1MehJQNkZXYEdGVzdABe2WPHgtpOygzhnBr4saT1MhiUwAjVf6l6iUo8/DG35HlI/e1tAEWVHuDDv4I4AuKRiiFSD+0GhJxrdyQtc/Ymb2yuZOM0UmCgkH6YmjN5hrWb//BgZfuI7DxwtCbOgC9sO+mntw+LKcLc7dCezAKSeNRlhps+k9H4/der78DhYAAAKRAAAACAAAAA

`new Message(responseBytes).toString()`:
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37240
;; flags: qr aa rd ra ; qd: 1 an: 2 au: 2 ad: 1 

;; OPT PSEUDOSECTION: 
; EDNS: version: 0; flags: do ; udp: 4096
;; QUESTIONS:
;;	ctr-e50-1451931954322-0016-01-000002.dev.test., type = AAAA, class = IN

;; ANSWERS:
ctr-e50-1451931954322-0016-01-000002.dev.test.	30	IN	AAAA	::ffff:172.17.0.19
ctr-e50-1451931954322-0016-01-000002.dev.test.	30	IN	RRSIG	AAAA 8 3 30 20250727110647 20240727110647 41253 dev.test. eXMNFlD8uzlbZQYFzpwdDwjq8DwztoLltSDLWAUqFeRojIgmmZO09GnvhkvLtzofx1dVE4RwwNlHMSYTyDugyZ5EITHYlwup962ADgf3DLx0l7VzydwzNJ5wBSumg3C4tJ8ecvZe7Nw2kvng6BJQzOHFnQvkPITFIjE+d5Vsk+E=

;; AUTHORITY RECORDS:
dev.test.		30	IN	NS	unknown.
dev.test.		30	IN	RRSIG	NS 8 2 30 20250727110647 20240727110647 41253 dev.test. Xtljx4LaTsoM4Zwa+LGk9TIYlMAI1X+peolKPPwxt+R5SP3tbQBFlR7gw7+COALikYohUg/tBoSca3ckLXP2Jm9srmTjNFJgoJB+mJozeYa1m//wYGX7iOw8cLQmzoAvbDvpp7cPiynC3O3QnswCknjUZYabPpPR+P3Xq+/A4WA=

;; ADDITIONAL RECORDS:


;; Message size: 459 bytes

**Comment by ibauersachs** [comment]
Thanks. The RRSIG record seems to missing even before it is parsed into a `Message` instance, which probably means that `getRegistryDNS().generateReply(...)` doesn't generate it anymore.

I'm not sure I can follow the code without debugging it. If possible, can you follow how the response is constructed differently?

While browsing the code, IMO parts of RegistryDNS are in serious need of refactoring, specifically this line is really bad for performance:
https://github.com/pjfanning/hadoop/blob/trunk/hadoop-common-project/hadoop-registry/src/main/java/org/apache/hadoop/registry/server/dns/RegistryDNS.java#L1053
- At least the executor should be cached
- Or better yet, convert the code to use the async API of dnsjava
- The entire lock-stuff would not be needed anymore when using `LookupSession`

**Comment by pjfanning** [comment]
I am no expert on this lib or DNS generally.
I may be wrong but it appears that the Hadoop test registers the same registry setup with dnsjava 3.5.3 and 3.6.0.

`getRegistryDNS().generateReply()` seems to operate very similarly with dnsjava 3.5.3 and 3.6.0.

The Hadoop code approx does this.
```
    Zone zone = findBestZone(name);
    SetResponse sr = zone.findRecords(name, type);
    List<RRset> rrsets = sr.answers();
```

With dnsjava 3.5.3 and 3.6.0, we seem to get one rrset entry but they appear to be different.
dnsjava v3.5.3
```
2024-07-27 15:33:23,436 [main] INFO  dns.RegistryDNS (RegistryDNS.java:addAnswer(1396)) - found answers [{ ctr-e50-1451931954322-0016-01-000002.dev.test. 30 IN AAAA [::ffff:172.17.0.19] }]
```

dnsjava v3.6.0
```
2024-07-27 15:35:37,396 [main] INFO  dns.RegistryDNS (RegistryDNS.java:addAnswer(1396)) - found answers [{ httpd-1.test1.root.dev.test. 30 IN AAAA [::ffff:172.17.0.19] sigs: [AAAA 8 5 30 20250727143537 20240727143537 41253 dev.test. KjdYBT4M8B7VY46UgJPZtwXZqXRVs8ir9mqS9SJMmchy5DotTYDNmBsZUtcjaRwXdkd4/Du2WwCf5oQEKZxIxGTJtyO8AvE0KIytIIPSBJVIpkNwzNsJhC6ZhpW12DfFWzWsAhoOnx6+g6fOpRhPZXhGSCiAvFXGUrpdYARvGVA=] }]
```

**Comment by ibauersachs** [comment]
Okay, found it:

[org.apache.hadoop.registry.server.dns.RegistryDNS.RegistryCommand#exec](
https://github.com/pjfanning/hadoop/blob/f055f93cc3f961398c3852edb36819c48e0c3174/hadoop-common-project/hadoop-registry/src/main/java/org/apache/hadoop/registry/server/dns/RegistryDNS.java#L1685) calls ` rRset.addRR(rrsigRecord);`.
This doesn't work anymore with 3.6+ as all data returned from `Zone`, including the `RRset` from `zone.findExactMatch(record.getName(), record.getType())`, is a copy to keep `Zone`s thread safety guarantees.
The fix is simple though: just call `zone.addRecord(rrsigRecord);` instead.

(Btw. it's not easy to run these registry tests. The resource loading for test.private and the zone files is broken on Windows. And even getting there requires commenting out building native code, despite having VS2019 around and on the path

**Comment by pjfanning** [comment]
Thanks very much @ibauersachs - your suggestion seems to work.
