### ISSUE TITLE
TSIG record is not being added to the query

### ISSUE THREAD

**Issue by MonkeyDeCoo** [dnsjava/dnsjava#331]
Hi,

I am setting up a TSIG key for my resolver using `resolver.setTSIGKey(tsig)` and I am using the `lookup.run` framework which should add the TSIG record for me. However, when I checked the logs that is emitted from class `SimpleResolver` in `sendAsync`, I don't see a TSIG record being rendered in the query message body. I do see logs regarding `TSIG-HMAC rendered message` and `TSIG-HMAC variables` that display a set of byte array information. Can you help me understand why I am not able to see the TSIG in the query message?

**Comment by ibauersachs** [comment]
Can you please post a small sample reproducing your case and the corresponding log output?
