### ISSUE TITLE
Compiling with Java9: Module not found

### ISSUE THREAD

**Issue by chernser** [dnsjava/dnsjava#333]
Good day, 

We are using DNSJava in our library and we still support java 8 customers. After update to latest 3.6.1 version of DNSJava we are not able to compile anymore because of error: 

``` 
   module not found: org.dnsjava
``` 

The reason is that `module-info.class` in located in `META-INF/versions/11` in the jar instead of `META-INF/versions/9`. 
I've found similar issue that explains may be better the root cause: https://github.com/FasterXML/jackson-databind/issues/3380

Thanks in advance! 

PS: I will appreciate a fix in nearest release: there is a few vulnerabilities in the DNSJava release we are using so I need very urgently come up with a fix.

**Comment by ibauersachs** [comment]
I don't understand your issue. Either you compile for the classpath, then the module name and module-info are irrelevant. Or, you use the module path, then as of 3.6 dnsjava has a proper module declaration and not just an automatic-module-name like before 3.6.
If you compile against Java 8, just use the -release 8 compiler option.

The linked Jackson issue is similar, but I see 0 reason to add support for Java 9 or 10. They are EOL for years.

Please create a small reproducer Maven or Gradle project that demonstrates any issues with Java 8, 11, 17 or 21.

**Comment by chernser** [comment]
I will do it this week. 
We have multi release build for 9, 11 etc. Our library is shipped as module for java 9 and dnsjava only starts with java 11 so when we compile java 9 build it expects dnsjava to be a module but doesn't find it.

**Comment by ibauersachs** [comment]
Okay, now I at least understand the issue.

But why are you still building against Java 9 and not just 11? Nobody is using the non-LTS runtimes anymore...

**Comment by chernser** [comment]
We are deprecating its support but cannot drop support right now.

**Comment by ibauersachs** [comment]
Java 9 was EOL March 2018; Java 10 was EOL in September 2018. That was seven (!) years ago. End of story for me here, sorry.

**Comment by chernser** [comment]
np.
