### ISSUE TITLE
ClientSubnetOption

### ISSUE THREAD

**Issue by lifelong-creator** [dnsjava/dnsjava#336]
`#####`
public ClientSubnetOption(int sourcePrefixLength, int scopePrefixLength, InetAddress address) {
    super(EDNSOption.Code.CLIENT_SUBNET);

    this.family = Address.familyOf(address);
    this.sourcePrefixLength = checkMaskLength("source netmask", this.family, sourcePrefixLength);
    this.scopePrefixLength = checkMaskLength("scope netmask", this.family, scopePrefixLength);
    this.address = Address.truncate(address, sourcePrefixLength);

    if (!address.equals(this.address)) {
      throw new IllegalArgumentException("source netmask is not valid for address");
    }
  }
`#####`

For ipv4，Does the sourcePrefixLength have to be 32?
If the sourcePrefixLength is less than 32， for "address.equals(this.address)" will always be false.

`#####`
this.address = Address.truncate(address, sourcePrefixLength);
if (!address.equals(this.address)) {
      throw new IllegalArgumentException("source netmask is not valid for address");
}
`#####`
I don't understand what this code does.

Thanks.

**Comment by ibauersachs** [comment]
You must provide an IP address that is already masked. ClientSubnetOption validates that the incoming address matches the specification. E.g.

10.10.17.18/16 is invalid, the address is not masked

10.10.0.0/16 is valid, the address is masked

**Comment by lifelong-creator** [comment]
> You must provide an IP address that is already masked. ClientSubnetOption validates that the incoming address matches the specification. E.g.
> 
> 10.10.17.18/16 is invalid, the address is not masked
> 
> 10.10.0.0/16 is valid, the address is masked

oh，I see. thanks.
