### ISSUE TITLE
Why is the default size of PAYLOADSIZ 1280?

### ISSUE THREAD

**Issue by lifelong-creator** [dnsjava/dnsjava#339]
![image](https://github.com/user-attachments/assets/b22ca3bf-f22d-4a5b-97db-c4ba06ec8f8d)

Why is the default size of PAYLOADSIZ 1280? How is 1280 calculated?

Thanks.

**Comment by ibauersachs** [comment]
It's the minimum recommended size from https://datatracker.ietf.org/doc/html/rfc6891#section-6.2.3
