### ISSUE TITLE
addition of `globalping` tool

### ISSUE THREAD

**Issue by nick9822** [dnsjava/dnsjava#343]
I would like to add `globalping` like `dig` in `org.xbill.DNS.tools` as one of the tools. It can be a wonderful addition as it can help querying probes around the world simultaneously, so user is not limited to query through a specific server like `8.8.8.8`.

Apart from DNS queries (through `dig`), it can allow anyone to run other networking commands such as `ping`, `traceroute`, `dig`, `curl` and `mtr` on probes distributed all around the world. 

@ibauersachs Please have a look at https://www.jsdelivr.com/globalping and let me know your thoughts.

Thanks.

**Comment by ibauersachs** [comment]
Hi,

Thanks for the idea. This sounds like adding support for a proprietary service that doesn't have much to do with DNS in particular. It would also set a precedent of favoring a specific company.
So unless this is something based on an RFC that I missed, I likely wouldn't merge any PR.

-- Ingo

**Comment by nick9822** [comment]
Thanks for your prompt response.
