### ISSUE TITLE
Lookup for different records types in a single request

### ISSUE THREAD

**Issue by xlaussel** [dnsjava/dnsjava#344]
In order to validate mail domains, I am checking  if there are A or MX records associated. So I first look for a A records and then if empty for MX records. So I have 2 requests (and 2 timeouts id the domain is not OK).

Il think it would be great to add a Lookup Constructor (and internal stuff) for looking more than one record type in a single request:

```java
Lookup(String name, int[] types)
```

**Comment by ibauersachs** [comment]
This isn't possible with the DNS protocol (except for querying with ANY). Making two or more lookups in the background would just obscure things and you're better off just sticking with your two lookups. You can do them in parallel.
