### ISSUE TITLE
RelativeNameException since 3.6.2

### ISSUE THREAD

**Issue by eliddan** [dnsjava/dnsjava#346]
Since version 3.6.2, I have a `org.xbill.DNS.RelativeNameException` thrown when parsing a zone file to get a `Zone` instance.

```java
Zone zone = new Zone(zoneName, "my_zone_file");
```

The associated message is `org.xbill.DNS.RelativeNameException: '@' is not an absolute name`.

My zone file looks like this.
```
$TTL 600
my-zone.com. IN SOA ns1.foo.com. john.doe.foo.com. 2023110717 28800 7200 604800 7200

@ 86400 IN NS ns1.foo.com.
@ 86400 IN NS ns2.foo.com.
@ 86400 IN NS ns3.foo.com.
@ IN A 1.2.3.4
```

We can notice that there is no `$ORIGIN` directive, and it works well if it is present in the file before RR declarations. But I think this directive is not mandatory (there is an implicit `<zone_name>.` origin).

The issue appeared with version 6.3.2, so I suspect to be a side effect of #335.

**Comment by ibauersachs** [comment]
Sorry about that. I'll have a look, but it'll take some time.

**Comment by eliddan** [comment]
Thank you for the fix !
