### ISSUE TITLE
Consider using Keep-a-Changelog spec

### ISSUE THREAD

**Issue by kentros** [dnsjava/dnsjava#35]
First, I just want to say that the existing plain-text Changelog file is a thing of beauty, IMO.  Anyone can quickly see what's changed over time.  Going forward, are we going to continue keeping this curated high-level change log up-to-date?

I recently stumbled on the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) project, and it seems like a great fit here.  The existing Changelog is already very similar. 

The proposed change is to convert the existing `Changelog` to markdown and rename it `CHANGELOG.md` and do some minor refactoring to consolidate the release versions according to the spec.  The advantage is:
* Markdown can allow better linking from the text directly to the code
* Can better seamlessly tie into website documentation and automatically render appropriately with a site theme.
* Follows a nice standard
* Allows for a nice place to communicate to consumers if we follow [Semantic Versioning](https://semver.org/spec/v2.0.0.html) and other notes about the version(s) and unreleased changes.

Thoughts?  Objections?  Agreement?

**Comment by ibauersachs** [comment]
I don't see much point in a conversion to markdown, but I'll try to update it again in my next changes and definitely before a release.
