### ISSUE TITLE
Possible TCP port leak

### ISSUE THREAD

**Issue by nlopes-r7** [dnsjava/dnsjava#351]
Greetings,

I would like to clarify a behavior of the lib.

**The scenario is:**
I have a fuzzer application (Python script) running TCP/UDP server on several ports, including 53. It is sending random data.
On the other side, I have a simple application which tries to connect with the fuzzer machine as if it would be a DNS server.

**Test steps are:**
1 - Created a `SimpleResolver` (TCP)
2 - Used it to query for `versions.bind`
3 - Got an exception (`java.io.IOException: Timed out while trying to resolve version.bind./TXT, id=44303 at org.xbill.DNS.Resolver.send(Resolver.java:172)`) - as expected (the server never intended to send valid data)
4 - On the catch block of the exception, I call `NioClient.close()`
5 - I leave the thread running after this

**Result:**
Querying netstat returns a `ESTABLISHED` connection between the fuzzer and my application on port 53 with a high Recv-Q of unprocessed data.

This connection is never dropped, unless JVM is shutdown. In my case, the server also doesn't attempt to close the connection (well, it is a fuzzer, it is not supported to act nicely).

If I try the same test but with UDP resolver, there are no hanging connections after the exception is thrown.

**My main concern here is:** I cannot see a way how to drop these TCP connections, unless I kill my application.

Any advice? Thank you

**Comment by ibauersachs** [comment]
Can you please share your fuzzer script or another simple reproducer? This would make it easier to debug.

I'll have a look anyway, but it'll take some time.

**Comment by nlopes-r7** [comment]
Sure. I have made a simple reproducer. It's not the original code, but it behaves the same.

**Python TCP/53 server fuzzer**
```
import socket
import os

def start_tcp_server(host='0.0.0.0', port=53):
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_socket.bind((host, port))
    server_socket.listen(1)
    print "Server listening on {}:{}".format(host, port)

    while True:
        client_socket, client_address = server_socket.accept()
        print "Connection established with {}".format(client_address)
        try:
            while True:
                data = os.urandom(65 * 1024)
                client_socket.sendall(data)
        except (socket.error, IOError):
            print "Connection with {} lost.".format(client_address)
        finally:
            client_socket.close()

if __name__ == "__main__":
    start_tcp_server()
```

**Java client based on example "Simple lookup with a Resolver"**
```
import org.xbill.DNS.*;
import java.net.UnknownHostException;

public class Main {
    public static void main(String[] args) throws UnknownHostException, TextParseException, InterruptedException {

        // Simple reproducer based on example "Simple lookup with a Resolver"
        Record queryRecord = Record.newRecord(Name.fromString("dnsjava.org."), Type.A, DClass.IN);
        Message queryMessage = Message.newQuery(queryRecord);

        Resolver r = new SimpleResolver("10.1.10.25"); // Replace with IP of machine running the fuzzer
        r.setPort(53);
        r.setTCP(true);
        try
        {
            r.sendAsync(queryMessage)
                    .whenComplete(
                            (answer, ex) -> {
                                if (ex == null) {
                                    System.out.println(answer);
                                } else {
                                    ex.printStackTrace();
                                }
                            })
                    .toCompletableFuture()
                    .get();
        }
        catch(Exception ex)
        {
            System.out.println("Exception was caught, closing the connection.");
            NioClient.close();
        }

        while(true)
        {
            System.out.println("Sleeping...");
            Thread.sleep(4000);
        }
    }
}
```

**Comment by nlopes-r7** [comment]
Hi, just wondering, is there any estimate of when version 3.6.3 (which includes this fix), will be released? Thank you very much!

**Comment by ibauersachs** [comment]
I released it last Sunday...
