### ISSUE TITLE
Missing / Needed new CAA tag types

### ISSUE THREAD

**Issue by klingon-hunter** [dnsjava/dnsjava#360]
Our developers for our domain erp use dnsjava.
Under CAA RR type 2 new tags are missing / needed 
issuevmc
issuemail

https://www.iana.org/assignments/pkix-parameters/pkix-parameters.xhtml#caa-properties

**Comment by ibauersachs** [comment]
dnsjava currently doesn't define any of these tag strings as constants, and the CAARecord accepts any string for the tag.

What exactly do you need?

**Comment by klingon-hunter** [comment]
closing as this was somewhat a wild goose. Developer sorted it and gave me wrong information. Apologies for that.
