### ISSUE TITLE
Use TextParseException and remove private TokenizerException

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#38]
Originally seen from question on SO:
https://stackoverflow.com/questions/55328043/dns-java-no-text-format-defined-for-tsig

TSIGRecord just throws an exception on rdataFromString:
https://github.com/dnsjava/dnsjava/blob/fa775c5fb8013b83c686204b1dafd83db0ce2fb0/org/xbill/DNS/TSIGRecord.java#L93

I think we could definitely implement the method, assuming each rdata field is separated by whitespace, following the example from the original post (and also adding a test for the other case when it's BADTIME)

Example:
```
Algorithm Name            Time       F   MS MAC                      OrgID Error   OL Other Data  
hmac-md5.sig-alg.reg.int. 1553302104 300 16 YWDHVhM3MpeTglOvyaj5fA== 27955 NOERROR 0
```

**Comment by bwelling** [comment]
There is no standard text format defined in the RFC, because TSIG records are not supposed to be in master files. We shouldn’t just make something up, or add support for a nonstandard format that someone else made up.

**Comment by kingle** [comment]
> a nonstandard format that someone else made up.

But didn't dnsjava already make one up?  rrToString already implements a conversion to a string from rdata.  I assumed we could have symmetry and allow that toString representation to feed into the fromString ?

https://github.com/dnsjava/dnsjava/blob/fa775c5fb8013b83c686204b1dafd83db0ce2fb0/org/xbill/DNS/TSIGRecord.java#L98

**Comment by bwelling** [comment]
Not having a toString() for an object is pretty obnoxious. But there is no standard format, so we shouldn’t pretend that there is. There isn’t any legitimate reason for a TSIG record to be in a zone file, and parsing one would violate the DNS specs.

**Comment by kingle** [comment]
Is there a singular source one can reference to see what is allowed or not allowed in a zone file?

**Comment by ibauersachs** [comment]
Even if it isn't allowed in a zone file, parsing a record from a string is something that should be possible. Delegating this to an external parser doesn't make sense.
If it shouldn't be in a zone file, the `Master`-class could reject TSIG (and whatever else that doesn't belong there) during parsing.

**Comment by kingle** [comment]
Fixed in https://github.com/dnsjava/dnsjava/commit/25fc5e0f5e103adc38b544010e16d804421f61b2
