### ISSUE TITLE
The Lookup class function getResult should also return the time taken to run the dns query

### ISSUE THREAD

**Issue by vineyy** [dnsjava/dnsjava#4]
The [Lookup.getResult()](http://www.dnsjava.org/doc/org/xbill/DNS/Lookup.html#getResult()) should also return the time taken to run the query.

**Comment by ibauersachs** [comment]
As explained in the README (you did read that, right?) this repo is only a Git mirror of the upstream project at http://sourceforge.net/projects/dnsjava/. Please report your problem there.
