### ISSUE TITLE
Reduce visibility of Master _nextRecord

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#43]
The Master class has a `nextRecord` and a `_nextRecord` method, both public.  If this `_nextRecord` is meant to be internal-only, we should reduce its visibility in the next major release to avoid confusion.  If we want to keep it public for passivity, we should mark it as deprecated.

**Comment by bwelling** [comment]
The fact that it's public was likely a refactoring error; it should be internal only.
