### ISSUE TITLE
Formally Deprecate Serial.increment method

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#46]
> I'm not completely sure why I added Serial.increment (in 2003), other than the fact that it seemed potentially useful.  Perhaps it should just be removed.

_Originally posted by @bwelling in https://github.com/dnsjava/dnsjava/pull/45#issuecomment-497162579_

With [unsignedCompare](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#compareUnsigned-int-int-) and other unsigned operations added in Java 8, I think we could formally deprecate this class altogether.

**Comment by ibauersachs** [comment]
There's more to it than just (un)signed comparison, which is why I deleted my comment. See e.g. https://en.wikipedia.org/wiki/Serial_number_arithmetic for a more "english" explanation than the RFCs.

**Comment by bwelling** [comment]
I agree with @ibauersachs; the main use of Serial is for comparisons.  Deprecating Serial.increment() would probably be ok, though.
