### ISSUE TITLE
Move or Enhance command line utils

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#52]
There are 4 command line java programs (dig, jnamed, lookup, and update) that are currently at the default package level.  For many (most?) consumers, these classes are useless in the jar.  We can't import these classes.  They seemed to be geared for a different audience.

There are a few options that come to mind:
1. Move these to a different repo (or make this repo a reactor with a tools module), for users who use them (dnsjava-tools?)
2. Use maven-assembly-plugin to help bundle an extra zip file at release along with scripts that include the appropriate java commands to invoke the tools OR create executable fat jars.
3. AOT compile into native executables and released separate from the main jar?

**Comment by ibauersachs** [comment]
They can still be accessed by executing Java directly and putting only dnsjava on the classpath: `java -cp dnsjava-2.1.9.jar dig`.

**Comment by kingle** [comment]
We could put these classes into a proper namespace and add a Main-Class to the manifest to allow one to invoke this as a executable jar --  e.g.: `java -jar dnsjava-3.0.0.jar dig .`

**Comment by ibauersachs** [comment]
Sure, why not.
