### ISSUE TITLE
Support more resolv.conf options/overrides

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#57]
According to the resolv.conf [man page](http://man7.org/linux/man-pages/man5/resolv.conf.5.html), there are a lot of options.  We should consider if we want to grab additional options, aside from the ndots we grab currently.

In addition, we should honor the environment variables overrides in the ResolverConfig:
```
       The search keyword of a system's resolv.conf file can be overridden
       on a per-process basis by setting the environment variable
       LOCALDOMAIN to a space-separated list of search domains.

       The options keyword of a system's resolv.conf file can be amended on
       a per-process basis by setting the environment variable RES_OPTIONS
       to a space-separated list of resolver options as explained above
       under options.
```

**Comment by TimEvens** [comment]
+1 for RES_OPTIONS. 

We are running into an issue with ResolverConfiguration [ResolverConfig Line 55](https://github.com/dnsjava/dnsjava/blob/master/src/main/java/org/xbill/DNS/ResolverConfig.java#L55) calls ```findSunJVM()``` and if true, returns without calling ```findUnix()```  to load ```/etc/resolv.conf```.   While this works fine for **nameservers** and **search domains** it doesn't work for **ndots**.  Apparently ```findSunJVM()``` does not load options and therefore does not set the correct **ndots** value as configured.   ```InetAddress.getByName()``` works fine when loading ndots.
