### ISSUE TITLE
Android O support

### ISSUE THREAD

**Issue by itayloryan** [dnsjava/dnsjava#6]
Since Android O removed net.dns1/2/3/4, now the dns look up dose not work on Android O devices, could you introduce Android O support?

**Comment by ibauersachs** [comment]
As explained in the README (you did read that, right?) this repo is only a Git mirror of the upstream project at http://sourceforge.net/projects/dnsjava/. Please report your problem there.

**Comment by kingle** [comment]
Should we re-open this one now?  Oreo killed the old mechanism: https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri

There seems to be a suggested "patch" (that even calls dnsjava out): https://stackoverflow.com/a/48973823/5420880

Do we want to pursue implementing the new method(s) for Android?

**Comment by ibauersachs** [comment]
No. I'm not going to pull in the Android SDK. The servers that dnsjava uses can be configured with system properties (i.e. `dns.server` and `dns.search`). I'm however open to suggestions for improving ResolverConfig (for > 2.1.9).

**Comment by kentros** [comment]
We should update the readme and javadoc to communicate that.  This will probably be a common question in the near future.

**Comment by ibauersachs** [comment]
Feel free to open a PR which adds a section to the readme or links to an FAQ.md.

**Comment by udittmer** [comment]
I offer the attached ResolverConfig.findAndroid method as a solution. It uses Brian's reflection approach to deal with Android classes, and has a switch for use on pre/post Oreo versions. 

```
/**
 * Parses the output of getprop, which is the only way to get DNS
 * info on Android. getprop might disappear in future releases, so
 * this code comes with a use-by date.
 */
private void
findAndroid() {
	// This originally looked for all lines containing .dns; but
	// http://code.google.com/p/android/issues/detail?id=2207#c73 indicates
	// that net.dns* should always be the active nameservers, so we use those.
	// Starting with Android 8 (API 26), the net.dns[1234] properties are no longer available:
	// https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri
	final String re1 = "^\\d+(\\.\\d+){3}$";
	final String re2 = "^[0-9a-f]+(:[0-9a-f]*)+:[0-9a-f]+$";
	ArrayList lserver = new ArrayList();
	ArrayList lsearch = new ArrayList();
	try {
		Class Version = Class.forName("android.os.Build$VERSION");
		Field SDK_INT = Version.getField("SDK_INT");

		if (SDK_INT.getInt(null) >= 26) {
			if (context != null) {
				Class Context = Class.forName("android.content.Context");
				Method getSystemService = Context.getDeclaredMethod("getSystemService", new Class[] { String.class });
				Object cm = getSystemService.invoke(context, "connectivity");

				Class ConnectivityManager = Class.forName("android.net.ConnectivityManager");
				Method getActiveNetwork = ConnectivityManager.getDeclaredMethod("getActiveNetwork", null);
				Object network = getActiveNetwork.invoke(cm, null);

				Class Network = Class.forName("android.net.Network");
				Method getLinkProperties = ConnectivityManager.getDeclaredMethod("getLinkProperties", new Class[] { Network });
				Object lp = getLinkProperties.invoke(cm, network);

				Class LinkProperties = Class.forName("android.net.LinkProperties");
				Method getDnsServers = LinkProperties.getDeclaredMethod("getDnsServers", null);
				List<InetAddress> addresses = (List<InetAddress>) getDnsServers.invoke(lp, null);

				for (InetAddress ineta : addresses) {
					// ineta can be an IPv4 or IPv6 address, so we do a quick check whether it's reachable. 200ms is an arbitrary limit.
					if (ineta.isReachable(200)) {
						lserver.add(ineta.getHostAddress());
					}
				}
			}
		} else {
			Class SystemProperties = Class.forName("android.os.SystemProperties");
			Method method = SystemProperties.getMethod("get", new Class[] { String.class });
			final String [] netdns = new String [] {"net.dns1", "net.dns2", "net.dns3", "net.dns4"};
			for (int i = 0; i < netdns.length; i++) {
				Object [] args = new Object [] { netdns[i] };
				String v = (String) method.invoke(null, args);
				if (v != null &&
					(v.matches(re1) || v.matches(re2)) &&
					!lserver.contains(v))
					lserver.add(v);
			}
		}
	} catch ( Exception e ) {
		e.printStackTrace();
		// ignore resolutely
	}
	configureFromLists(lserver, lsearch);
}

```

Unfortunately it introduces a slight complication that I don't know how to avoid: it needs an Android Context object to work with. So it also needs the following, where the refresh(ctx) needs to be called during app initialization.

```
private static Object context = null;

/** Gets the current configuration */
public static void
refresh (Object ctx) {
	context = ctx;
	refresh();
}
```

I have tested this on both pre-Oreo and port-Oreo devices, and it seems to work fine. The 200ms timeout for isReachable is arbitrary; someone who knows more than me about how DNS works may be able to suggest a different value. Let me know what you think.

**Comment by udittmer** [comment]
Any chance of this getting included? Is more information needed, or can I help with anything?

**Comment by ibauersachs** [comment]
The patch as-is isn't going to work. The is-reachable code e.g. is nonsense, a DNS server is not necessarily pingable. I'm also not a fan of adding the refresh overload. I was hoping to resolve this with the SPI refactoring of the whole config lookup.

**Comment by wlxyhy** [comment]
> I offer the attached ResolverConfig.findAndroid method as a solution. It uses Brian's reflection approach to deal with Android classes, and has a switch for use on pre/post Oreo versions.
> 
> ```
> /**
>  * Parses the output of getprop, which is the only way to get DNS
>  * info on Android. getprop might disappear in future releases, so
>  * this code comes with a use-by date.
>  */
> private void
> findAndroid() {
> 	// This originally looked for all lines containing .dns; but
> 	// http://code.google.com/p/android/issues/detail?id=2207#c73 indicates
> 	// that net.dns* should always be the active nameservers, so we use those.
> 	// Starting with Android 8 (API 26), the net.dns[1234] properties are no longer available:
> 	// https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri
> 	final String re1 = "^\\d+(\\.\\d+){3}$";
> 	final String re2 = "^[0-9a-f]+(:[0-9a-f]*)+:[0-9a-f]+$";
> 	ArrayList lserver = new ArrayList();
> 	ArrayList lsearch = new ArrayList();
> 	try {
> 		Class Version = Class.forName("android.os.Build$VERSION");
> 		Field SDK_INT = Version.getField("SDK_INT");
> 
> 		if (SDK_INT.getInt(null) >= 26) {
> 			if (context != null) {
> 				Class Context = Class.forName("android.content.Context");
> 				Method getSystemService = Context.getDeclaredMethod("getSystemService", new Class[] { String.class });
> 				Object cm = getSystemService.invoke(context, "connectivity");
> 
> 				Class ConnectivityManager = Class.forName("android.net.ConnectivityManager");
> 				Method getActiveNetwork = ConnectivityManager.getDeclaredMethod("getActiveNetwork", null);
> 				Object network = getActiveNetwork.invoke(cm, null);
> 
> 				Class Network = Class.forName("android.net.Network");
> 				Method getLinkProperties = ConnectivityManager.getDeclaredMethod("getLinkProperties", new Class[] { Network });
> 				Object lp = getLinkProperties.invoke(cm, network);
> 
> 				Class LinkProperties = Class.forName("android.net.LinkProperties");
> 				Method getDnsServers = LinkProperties.getDeclaredMethod("getDnsServers", null);
> 				List<InetAddress> addresses = (List<InetAddress>) getDnsServers.invoke(lp, null);
> 
> 				for (InetAddress ineta : addresses) {
> 					// ineta can be an IPv4 or IPv6 address, so we do a quick check whether it's reachable. 200ms is an arbitrary limit.
> 					if (ineta.isReachable(200)) {
> 						lserver.add(ineta.getHostAddress());
> 					}
> 				}
> 			}
> 		} else {
> 			Class SystemProperties = Class.forName("android.os.SystemProperties");
> 			Method method = SystemProperties.getMethod("get", new Class[] { String.class });
> 			final String [] netdns = new String [] {"net.dns1", "net.dns2", "net.dns3", "net.dns4"};
> 			for (int i = 0; i < netdns.length; i++) {
> 				Object [] args = new Object [] { netdns[i] };
> 				String v = (String) method.invoke(null, args);
> 				if (v != null &&
> 					(v.matches(re1) || v.matches(re2)) &&
> 					!lserver.contains(v))
> 					lserver.add(v);
> 			}
> 		}
> 	} catch ( Exception e ) {
> 		// ignore resolutely
> 	}
> 	configureFromLists(lserver, lsearch);
> }
> ```
> 
> Unfortunately it introduces a slight complication that I don't know how to avoid: it needs an Android Context object to work with. So it also needs the following, where the refresh(ctx) needs to be called during app initialization.
> 
> ```
> private static Object context = null;
> 
> /** Gets the current configuration */
> public static void
> refresh (Object ctx) {
> 	context = ctx;
> 	refresh();
> }
> ```
> 
> I have tested this on both pre-Oreo and port-Oreo devices, and it seems to work fine. The 200ms timeout for isReachable is arbitrary; someone who knows more than me about how DNS works may be able to suggest a different value. Let me know what you think.

That works, infect, you don't have to use reflect, just use it like this:
`ConnectivityManager connectivityManager = context.getSystemService(ConnectivityManager.class);
            Network network = connectivityManager.getActiveNetwork();
            LinkProperties linkProperties = connectivityManager.getLinkProperties(network);
            List<InetAddress> dnsServers = linkProperties.getDnsServers();
            for (InetAddress addr : dnsServers) {
                lserver.add(addr.getHostAddress());
            }`

**Comment by udittmer** [comment]
Good to hear that it works for others as well. Reflection is necessary because the DNSJava library is not built specifically for Android, but is supposed to work in non-Android environments as well. And what's more, it's a prerequisite that the build process should not reference the Android jar file, so classes can't be used directly.

But since the patch isn't going in, I continued to work with my patched-up version of DNSJava rather than the official one.

**Comment by ibauersachs** [comment]
It's not not going in, just not in this form.

**Comment by camhart** [comment]
I would love to see this PR merged yesterday.
