### ISSUE TITLE
API changes report for dnsjava

### ISSUE THREAD

**Issue by lvc** [dnsjava/dnsjava#7]
The review of API changes for the dnsjava library since 1.2.3 version: https://abi-laboratory.pro/java/tracker/timeline/dnsjava/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/dnsjava/dnsjava/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![dnsjava-2](https://user-images.githubusercontent.com/1517837/31113283-3161d2a6-a821-11e7-8f2d-a4d782ff90f5.png)
![dnsjava-1](https://user-images.githubusercontent.com/1517837/31113282-31595130-a821-11e7-8a90-9435b8dbea53.png)

**Comment by ibauersachs** [comment]
Thanks. Since this repo is only a SVN mirror from SourceForge, you might want to notify Brian on the mailing list about these reports.
