### ISSUE TITLE
OSGI issues for non Android apps

### ISSUE THREAD

**Issue by vikinghawk** [dnsjava/dnsjava#70]
"android.os" is listed as a required import-package in the manifest, so using dnsjava in OSGI environments outside of Android does not work.

Any reason this couldn't be changed to be an optional import?

**Comment by ibauersachs** [comment]
This isn't intentional and slipped through before releasing 2.1.9.

As a workaround you can provide `android.os` as an extra system package, e.g. for Apache Felix:  `org.osgi.framework.system.packages.extra=android.os`.

**Comment by maximusfloydus** [comment]
@ibauersachs When do you plan to cut another release?

**Comment by ibauersachs** [comment]
I don't really have a plan :-)

Is this so important that it warrants a release on its own? Does the workaround not work for you?
