### ISSUE TITLE
Please don't overwrite the error info for IOException when doing lookup without one hint

### ISSUE THREAD

**Issue by sallyslove** [dnsjava/dnsjava#71]
Check the file org.xbill.DNS.Lookup.java. In the function private void lookup(Name current)

           try {
                response = this.resolver.send(query);
            } 
           catch (IOException var7) {
                  ....
                } else {
                    this.networkerror = true;
                }

                return;

It overwrites the original error info without even one log. I have to guess what kind of IOException when I get "network error".

Could we add one log here to make it easier to debug?

**Comment by sallyslove** [comment]
And as it is open source, so everyone could change it ?

**Comment by ibauersachs** [comment]
> And as it is open source, so everyone could change it ?

Well then, where is your pull request? ;-)

**Comment by sallyslove** [comment]
I create one. Please let me know whether it works. Thanks

**Comment by sallyslove** [comment]
And，I think I may encounter another issue. I restricted local port by:
((SimpleResolver) resolver).setLocalAddress(new InetSocketAddress(port));

There seems under some condition, the connection is not released. And the port is occupied for a long time in TIME_WAIT.

I am still struggle with it

**Comment by sallyslove** [comment]
Hi, the pull request fails. But from BT structure, I find no proper file to add one BT just for the log.

Would you please offer some hint? Also, I see no mockito or powermock similar tool in BT. It is not so easy to sim one IOException here.
