### ISSUE TITLE
AddressTest fails

### ISSUE THREAD

**Issue by lagrwilson** [dnsjava/dnsjava#77]
I cloned the project and ran maven -U clean package and I got 

[ERROR] Failures: 
[ERROR]   AddressTest.test_getAllByName_invalid:339 Expected java.net.UnknownHostException to be thrown, but nothing was thrown.
[ERROR]   AddressTest.test_getByName_invalid:315 Expected java.net.UnknownHostException to be thrown, but nothing was thrown.
[ERROR]   AddressTest.test_getHostName:355 Expected java.net.UnknownHostException to be thrown, but nothing was thrown.

**Comment by lagrwilson** [comment]
Also the jar has version 2.9. I was expecting 3.0.0-Snapshot.

**Comment by ibauersachs** [comment]
Some of the tests unfortunately query actual nameservers and thus may fail in some networks. On your network the name `example.invalid` seems to be resolvable, which it shouldn't be.

There was never a 2.9 version, the last released version is 2.1.9, Not sure where or why you'd get 2.9.

**Comment by lagrwilson** [comment]
I didn't recognize how unmavenized this project was.  I cloned it, add maven wrapper directories to this project,  and now it runs mvn clean package just fine. Then I moved the 3.0.0.-Snapshot jar to my local maven repository.  

Please fix the unit test.

**Comment by lagrwilson** [comment]
And FYI, I am running with Java 1.8.

**Comment by ibauersachs** [comment]
Unmavenized? There's a complete, working pom.xml, what else could you possibly want?

This is an open source project, how about contributing rather than just putting up an insolent demand?
