### ISSUE TITLE
Resolver on non-default port

### ISSUE THREAD

**Issue by avmusa** [dnsjava/dnsjava#80]
`org.xbill.DNS.SimpleResolver` and `org.xbill.DNS.ExtendedResolver` work only on a default port (53).
Whilst custom port can be set with `org.xbill.DNS.SimpleResolver.setPort(int)`, it is not supported in the `org.xbill.DNS.ExtendedResolver`.

When I pass `-Ddns.server=1.2.3.4:5300` it's failing because `1.2.3.4:5300` is used for the hostname with default port (53).

**Comment by bwelling** [comment]
Both `SimpleResolver` and `ExtendedResolver` support alternate ports; `setPort()` is part of the `Resolver` interface, and is implemented by both.

The `dns.server` command line options do not support alternate ports, never have, and are not documented as such.  They were intended as a way to manually override the name servers typically provided by the operating system, which do not include alternate ports.

Even if they did support alternate ports, it would not be using the `1.2.3.4:5300` syntax, as that would not support IPv6 (an IPv6 address with a port would be ambiguous).

**Comment by ibauersachs** [comment]
IPv6 addresses would need to be specified as e.g. `[2001:db8::1]:53`. The entire resolver configuration will be overhauled/rewritten for v3, see #8. Not sure yet if I'll do another 2.x release and if this would make it there.
