### ISSUE TITLE
Lookup cache hit

### ISSUE THREAD

**Issue by transilvlad** [dnsjava/dnsjava#81]
Provide a way to tell if a lookup was resolved or loaded from cache.

**Comment by ibauersachs** [comment]
How would you like to obtain such an information and to what should it relate? A result could be (partially) from the cache at any point in time during the lookup. Consider e.g. `test.example.com./CNAME` -> `www.example.com./A`, where the A record was cached in an earlier lookup, but the CNAME was not.
