### ISSUE TITLE
Support for RFC6891, EDNS(0)

### ISSUE THREAD

**Issue by vijaykam** [dnsjava/dnsjava#83]
Hello,
Does 'dnsjava' currently support EDNS(0) as described in RFC6891. This rfc obsoletes RFCs 2671,2673. 
In case it does not, is it planned to be supported? Glad to contribute if required!

**Comment by ibauersachs** [comment]
Generally dnsjava supports EDNS, but I haven't compared the RFCs and there might be omissions or discrepancies. Have you noticed anything specific?

**Comment by ibauersachs** [comment]
I couldn't find anything missing or wrong w.r.t. RFC6891. a2b3062 now enables EDNS0 by default, and d311ac0 added missing EDNS opt codes.
