### ISSUE TITLE
java.net.UnknownHostException:

### ISSUE THREAD

**Issue by venjirai** [dnsjava/dnsjava#97]
I'm using your library with OkHttp's .dns() method.
After upgrading from 2.1.9 to 3.0.2 I get the following exception when first starting a lookup:

W/System.err: java.net.UnknownHostException: <myapi.mydomain.com> could not be resolved
W/System.err:     at org.xbill.DNS.Address.lookupHostName(Address.java:270)
W/System.err:     at org.xbill.DNS.Address.getByName(Address.java:309)

After the first lookup all further lookups are successful.
I'm using Google DNS 
Resolver googleFirstResolver = new SimpleResolver("8.8.8.8");

**Comment by ibauersachs** [comment]
I'm sorry, but could you please be a bit more specific? I don't know OkHttp but after some googling I couldn't find how they use dnsjava. If this is custom code, please add an example so that I can reproduce this, e.g. an example Maven/Gradle project.
